-- GENERATED BY SUGARMAGIC - DO NOT EDIT
-- SUGARMAGIC SUPABASE MIGRATIONS TEMPLATE VERSION: 1

-- Plan 047 §47.8 — SugarProfile's owned schema.
-- public.saves: cross-plugin player state (region, position, quest)
-- public.profiles: per-user authored data (display_name, locale, preferences)
-- on_auth_user_created trigger: every new auth.users row gets a profiles row

create table if not exists public.saves (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_played timestamptz not null default now(),
  schema_version integer not null default 1,
  payload jsonb not null default '{}'::jsonb
);

alter table public.saves enable row level security;

create policy "users select own saves" on public.saves
  for select using (auth.uid() = user_id);
create policy "users insert own saves" on public.saves
  for insert with check (auth.uid() = user_id);
create policy "users update own saves" on public.saves
  for update using (auth.uid() = user_id);
create policy "users delete own saves" on public.saves
  for delete using (auth.uid() = user_id);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  locale text not null default 'en',
  preferences jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "users select own profile" on public.profiles
  for select using (auth.uid() = user_id);
create policy "users insert own profile" on public.profiles
  for insert with check (auth.uid() = user_id);
create policy "users update own profile" on public.profiles
  for update using (auth.uid() = user_id);

create or replace function public.handle_new_user()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
begin
  insert into public.profiles (user_id)
    values (new.id)
    on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
