-- GENERATED BY SUGARMAGIC - DO NOT EDIT
-- Owned by the sugarlang plugin.

-- A player's learner state. One row per player per language pair.
create table if not exists public.sugarlang_learner (
  user_id uuid not null references auth.users(id) on delete cascade,
  record_key text not null,
  target_language text not null,
  support_language text not null,
  estimated_cefr_band text not null,
  assessment_status text not null,
  evaluated_cefr_band text,
  cefr_confidence double precision not null default 0,
  evaluated_at bigint,
  deleted boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, record_key)
);

-- Every word a player has met, with the numbers that schedule it.
create table if not exists public.sugarlang_words (
  user_id uuid not null references auth.users(id) on delete cascade,
  -- The lemma id.
  record_key text not null,
  difficulty double precision not null default 0,
  stability double precision not null default 0,
  -- retrievability is NOT stored: it is a function of elapsed time, so a
  -- stored value would decay from whenever it happened to be written.
  last_reviewed_at bigint,
  review_count integer not null default 0,
  lapse_count integer not null default 0,
  cefr_prior_band text not null default 'A1',
  prior_weight double precision not null default 0,
  productive_strength double precision not null default 0,
  last_produced_at bigint,
  provisional_evidence double precision not null default 0,
  provisional_evidence_first_seen_turn integer,
  deleted boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, record_key)
);

-- A sync asks 'what changed since?', so that is what is indexed.
create index if not exists sugarlang_learner_since_idx
  on public.sugarlang_learner (user_id, updated_at);
create index if not exists sugarlang_words_since_idx
  on public.sugarlang_words (user_id, updated_at);

-- What the teacher asks: which words at this level does this player
-- know? Unanswerable without this if the row were opaque JSON.
create index if not exists sugarlang_words_band_idx
  on public.sugarlang_words (user_id, cefr_prior_band);

alter table public.sugarlang_learner enable row level security;

create policy "users select own sugarlang_learner" on public.sugarlang_learner
  for select using (auth.uid() = user_id);
create policy "users insert own sugarlang_learner" on public.sugarlang_learner
  for insert with check (auth.uid() = user_id);
create policy "users update own sugarlang_learner" on public.sugarlang_learner
  for update using (auth.uid() = user_id);
create policy "users delete own sugarlang_learner" on public.sugarlang_learner
  for delete using (auth.uid() = user_id);

alter table public.sugarlang_words enable row level security;

create policy "users select own sugarlang_words" on public.sugarlang_words
  for select using (auth.uid() = user_id);
create policy "users insert own sugarlang_words" on public.sugarlang_words
  for insert with check (auth.uid() = user_id);
create policy "users update own sugarlang_words" on public.sugarlang_words
  for update using (auth.uid() = user_id);
create policy "users delete own sugarlang_words" on public.sugarlang_words
  for delete using (auth.uid() = user_id);

-- The client never writes updated_at. A device with a wrong clock would
-- otherwise win every conflict it took part in.
create or replace function public.sugarlang_touch_updated_at()
  returns trigger
  language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sugarlang_learner_touch on public.sugarlang_learner;
create trigger sugarlang_learner_touch
  before insert or update on public.sugarlang_learner
  for each row execute function public.sugarlang_touch_updated_at();

drop trigger if exists sugarlang_words_touch on public.sugarlang_words;
create trigger sugarlang_words_touch
  before insert or update on public.sugarlang_words
  for each row execute function public.sugarlang_touch_updated_at();

