-- GENERATED BY SUGARMAGIC - DO NOT EDIT
-- Owned by the sugarlang plugin.

-- The evidence behind a learner's level. Without it a returning player
-- holds a band with nothing supporting it, and the next thing they do
-- updates a fresh prior -- quietly discarding how the estimate was
-- reached.
--
-- json rather than columns: it is a fixed set of weights per level,
-- read and rewritten whole and never queried by. The word table is the
-- opposite case and gets real columns.
alter table public.sugarlang_learner
  add column if not exists cefr_posterior jsonb;

