# GENERATED BY SUGARMAGIC - DO NOT EDIT
# SUGARMAGIC TEMPLATE VERSION: 4

terraform {
  required_version = ">= 1.5"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.gcp_project_id
  region  = var.region

  # user_project_override + billing_project tell the provider to bill API
  # quota against the project we're managing (not against ADC's separately-
  # configured quota project). Without this, calls to APIs like orgpolicy
  # fail with "API requires a quota project" because ADC defaults to whatever
  # the user last set via `gcloud auth application-default set-quota-project`
  # — which a sugarmagic user should never have to think about. This makes
  # the terraform plan self-contained: it picks its own billing project from
  # the deployment variables, regardless of the user's local gcloud state.
  user_project_override = true
  billing_project       = var.gcp_project_id
}

# Artifact Registry — Docker repo for Cloud Run gateway images.
resource "google_artifact_registry_repository" "gateway" {
  location      = var.region
  repository_id = var.service_name_prefix
  description   = "Cloud Run gateway images for ${var.service_name_prefix}"
  format        = "DOCKER"
}

# Runtime service account — Cloud Run service runs as this identity at request time.
resource "google_service_account" "runtime" {
  account_id   = var.runtime_sa_account_id
  display_name = "Cloud Run runtime SA for ${var.service_name_prefix}"
}

# Workload Identity Federation pool for GitHub Actions.
resource "google_iam_workload_identity_pool" "github" {
  workload_identity_pool_id = "${var.service_name_prefix}-gh"
  display_name              = "GitHub OIDC pool"
  description               = "Lets GitHub Actions in ${var.github_repo} deploy this game"
}

resource "google_iam_workload_identity_pool_provider" "github" {
  workload_identity_pool_id          = google_iam_workload_identity_pool.github.workload_identity_pool_id
  workload_identity_pool_provider_id = "github"
  display_name                       = "GitHub OIDC"

  attribute_mapping = {
    "google.subject"       = "assertion.sub"
    "attribute.repository" = "assertion.repository"
    "attribute.actor"      = "assertion.actor"
  }

  attribute_condition = "attribute.repository == \"${var.github_repo}\""

  oidc {
    issuer_uri = "https://token.actions.githubusercontent.com"
  }
}

locals {
  github_principal = "principalSet://iam.googleapis.com/${google_iam_workload_identity_pool.github.name}/attribute.repository/${var.github_repo}"
}

# GitHub deploy identity gets the roles needed to push images, deploy Cloud Run, and reference secrets.
resource "google_project_iam_member" "github_run_admin" {
  project = var.gcp_project_id
  role    = "roles/run.admin"
  member  = local.github_principal
}

resource "google_project_iam_member" "github_artifactregistry_writer" {
  project = var.gcp_project_id
  role    = "roles/artifactregistry.writer"
  member  = local.github_principal
}

resource "google_project_iam_member" "github_secretmanager_viewer" {
  project = var.gcp_project_id
  role    = "roles/secretmanager.viewer"
  member  = local.github_principal
}

# GitHub identity can act-as the runtime SA so `gcloud run deploy --service-account` works.
resource "google_service_account_iam_member" "github_impersonates_runtime" {
  service_account_id = google_service_account.runtime.name
  role               = "roles/iam.serviceAccountUser"
  member             = local.github_principal
}

# Story 46.10 — google-github-actions/auth@v2 with
# `service_account: <runtime SA>` impersonates that SA by calling
# iam.serviceAccounts.getAccessToken, which requires
# roles/iam.serviceAccountTokenCreator (NOT just serviceAccountUser).
# Without this binding the GHA job fails with
# "Permission 'iam.serviceAccounts.getAccessToken' denied".
resource "google_service_account_iam_member" "github_impersonates_runtime_token_creator" {
  service_account_id = google_service_account.runtime.name
  role               = "roles/iam.serviceAccountTokenCreator"
  member             = local.github_principal
}

# Runtime SA can read Secret Manager values at request time.
resource "google_project_iam_member" "runtime_secret_accessor" {
  project = var.gcp_project_id
  role    = "roles/secretmanager.secretAccessor"
  member  = "serviceAccount:${google_service_account.runtime.email}"
}

# Empty Secret Manager containers — one per declared secret. Values are written separately
# via `gcloud secrets versions add` (Studio host action; never via terraform).
resource "google_secret_manager_secret" "containers" {
  for_each  = toset(var.secret_names)
  secret_id = each.value

  replication {
    auto {}
  }
}

# Story 45.5.7 — project-level org-policy override allowing the
# `allUsers` IAM member, so the Cloud Run gateway can be made
# publicly reachable. Requires `roles/orgpolicy.policyAdmin` at the
# org level for the deploying principal (granted by the
# create-gcp-project host action). The actual SERVICE-level binding
# (allUsers → roles/run.invoker on the deployed Cloud Run service)
# happens via deploy.sh's `gcloud run deploy --allow-unauthenticated`
# flag — that's the only correct level for an allUsers binding
# (project-level IAM rejects allUsers with PROJECT_SET_IAM_DISALLOWED_MEMBER_TYPE).
# Without THIS org-policy override, that flag fails silently.
resource "google_org_policy_policy" "allow_public_invokers" {
  name   = "projects/${var.gcp_project_id}/policies/iam.allowedPolicyMemberDomains"
  parent = "projects/${var.gcp_project_id}"
  spec {
    rules {
      allow_all = "TRUE"
    }
  }
}
