# GENERATED BY SUGARMAGIC - DO NOT EDIT
# SUGARMAGIC TEMPLATE VERSION: 4

output "artifact_registry_url" {
  description = "Artifact Registry Docker URL prefix for pushing gateway images"
  value       = "${var.region}-docker.pkg.dev/${var.gcp_project_id}/${google_artifact_registry_repository.gateway.repository_id}"
}

output "runtime_sa_email" {
  description = "Runtime service account email for `gcloud run deploy --service-account`"
  value       = google_service_account.runtime.email
}

output "github_wif_provider_name" {
  description = "Full WIF provider resource name for GitHub Actions `workload_identity_provider`"
  value       = google_iam_workload_identity_pool_provider.github.name
}

output "secret_names" {
  description = "Secret Manager secret IDs created by terraform (empty containers; values written via gcloud)"
  value       = [for s in google_secret_manager_secret.containers : s.secret_id]
}

output "allowed_origins" {
  description = "Comma-joined list of origins the gateway should accept for CORS. Set on Cloud Run via deploy.sh --set-env-vars."
  value       = var.allowed_origins
}
