# GENERATED BY SUGARMAGIC - DO NOT EDIT
# SUGARMAGIC TEMPLATE VERSION: 4

gcp_project_id        = "wordlark-v1-1dqlc"
region                = "us-central1"
service_name_prefix   = "wordlark-v1-1dqlc"
runtime_sa_account_id = "wordlark-v1-1dqlc-runtime"
github_repo           = "nikkileaps/wordlark"
secret_names          = [
  "wordlark-v1-1dqlc-anthropic-api-key",
  "wordlark-v1-1dqlc-openai-api-key"
]
allowed_origins       = [
  "https://*--wordlark-prod.netlify.app",
  "https://wordlark-prod.netlify.app"
]
