# GENERATED BY SUGARMAGIC - DO NOT EDIT
# SUGARMAGIC TEMPLATE VERSION: 4

variable "gcp_project_id" {
  description = "GCP project hosting this game's deployment slot"
  type        = string
}

variable "region" {
  description = "GCP region for Cloud Run and Artifact Registry"
  type        = string
}

variable "service_name_prefix" {
  description = "Prefix for derived resource names (Artifact Registry repo, Secret Manager containers, WIF pool)"
  type        = string
}

variable "runtime_sa_account_id" {
  description = "account_id (left of @) for the runtime service account"
  type        = string
}

variable "github_repo" {
  description = "GitHub owner/repo authorized to deploy via Workload Identity Federation"
  type        = string
}

variable "secret_names" {
  description = "Secret Manager secret IDs to create empty containers for"
  type        = list(string)
  default     = []
}

variable "allowed_origins" {
  description = "Origins the gateway echoes in Access-Control-Allow-Origin. Patterns may contain a single '*' for the Netlify per-deploy subdomain wildcard."
  type        = list(string)
  default     = []
}
