#!/usr/bin/env bash
# GENERATED BY SUGARMAGIC - DO NOT EDIT
# Re-save the project in Studio to regenerate this file.
# Intentionally NOT using `set -u` (nounset) — macOS ships bash 3.2 which
# treats expanding an empty array (`${arr[@]}`) as "unbound variable" and
# crashes the script before it does anything useful. The critical values
# that would benefit from `-u` (terraform outputs) are explicitly null-
# checked below; that's a stronger guard than `-u` would give us anyway.
set -eo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "[sugardeploy] jq is required to parse terraform outputs; install via brew/apt before running deploy.sh" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="${SCRIPT_DIR}/terraform"

if [ ! -d "${TERRAFORM_DIR}" ]; then
  echo "[sugardeploy] terraform directory not found at ${TERRAFORM_DIR}" >&2
  echo "[sugardeploy] run Setup Infra from the SugarDeploy workspace first" >&2
  exit 1
fi

# Read authoritative deploy-time values from terraform outputs. Terraform
# is the single source of truth for resolved resource names; we don't
# duplicate them here.
# Story 46.10 — env-vars-or-terraform resolution. GHA can't run
# terraform (no state in the runner; no terraform binary by default),
# so the workflow injects the three values it knows directly:
#   - SUGARMAGIC_RUNTIME_SA_EMAIL (already a repo VAR from 46.8)
#   - SUGARMAGIC_ARTIFACT_REGISTRY_URL (derived at workflow-gen time)
#   - SUGARMAGIC_ALLOWED_ORIGINS (derived at workflow-gen time)
# When ANY are missing (local dev runs deploy.sh by hand), we fall
# back to terraform output -json for the missing pieces.
NEED_TF=0
[ -z "${SUGARMAGIC_RUNTIME_SA_EMAIL:-}" ] && NEED_TF=1
[ -z "${SUGARMAGIC_ARTIFACT_REGISTRY_URL:-}" ] && NEED_TF=1
[ -z "${SUGARMAGIC_ALLOWED_ORIGINS:-}" ] && NEED_TF=1
TF_OUTPUTS=""
if [ "${NEED_TF}" = "1" ]; then
  if ! command -v terraform >/dev/null 2>&1; then
    echo "[sugardeploy] terraform is required to resolve deploy-time values when SUGARMAGIC_RUNTIME_SA_EMAIL / SUGARMAGIC_ARTIFACT_REGISTRY_URL / SUGARMAGIC_ALLOWED_ORIGINS are not all preset; install terraform or pre-set those env vars." >&2
    exit 1
  fi
  TF_OUTPUTS="$(terraform -chdir="${TERRAFORM_DIR}" output -json)"
fi
RUNTIME_SA_EMAIL="${SUGARMAGIC_RUNTIME_SA_EMAIL:-$(echo "${TF_OUTPUTS}" | jq -r '.runtime_sa_email.value')}"
ARTIFACT_REGISTRY_URL="${SUGARMAGIC_ARTIFACT_REGISTRY_URL:-$(echo "${TF_OUTPUTS}" | jq -r '.artifact_registry_url.value')}"
ALLOWED_ORIGINS="${SUGARMAGIC_ALLOWED_ORIGINS:-$(echo "${TF_OUTPUTS}" | jq -r '.allowed_origins.value | join(",")')}"

if [ -z "${ARTIFACT_REGISTRY_URL}" ] || [ "${ARTIFACT_REGISTRY_URL}" = "null" ]; then
  echo "[sugardeploy] terraform output 'artifact_registry_url' is empty; did Setup Infra finish?" >&2
  exit 1
fi
if [ -z "${RUNTIME_SA_EMAIL}" ] || [ "${RUNTIME_SA_EMAIL}" = "null" ]; then
  echo "[sugardeploy] terraform output 'runtime_sa_email' is empty; did Setup Infra finish?" >&2
  exit 1
fi

PROJECT_ID="${SUGARMAGIC_GCP_PROJECT_ID:-wordlark-v1-1dqlc}"
REGION="${SUGARMAGIC_GCP_REGION:-us-central1}"

# Secret bindings: env-var-name → Secret Manager secret id. The actual secret
# values live in Secret Manager (written via the SugarDeploy "Set Value" UI),
# NOT in this script. `--set-secrets` binds them at request time via the
# runtime SA's `roles/secretmanager.secretAccessor` grant (set up by
# terraform). Empty array when no plugin declares secrets.
SECRET_ARGS=(
  "--set-secrets=SUGARMAGIC_ANTHROPIC_API_KEY=wordlark-v1-1dqlc-anthropic-api-key:latest"
  "--set-secrets=SUGARMAGIC_GATEWAY_SHARED_TOKEN=wordlark-v1-1dqlc-gateway-shared-token:latest"
  "--set-secrets=SUGARMAGIC_OPENAI_API_KEY=wordlark-v1-1dqlc-openai-api-key:latest"
)

# Story 46.15 — non-secret runtime config env vars the gateway needs.
# Each entry reads its value from deploy.sh's own process env at run
# time (set by the GHA workflow or by the Studio host action that
# spawned this script). Keys whose env value is empty are SKIPPED to
# avoid setting EMPTY env on Cloud Run (which would shadow a future
# default the gateway might bake in).
RUNTIME_CONFIG_PAIRS=()
RUNTIME_CONFIG_PAIRS+=("SUGARMAGIC_SUGARAGENT_ANTHROPIC_MODEL=${SUGARMAGIC_SUGARAGENT_ANTHROPIC_MODEL:-}")
RUNTIME_CONFIG_PAIRS+=("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID=${SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID:-}")
RUNTIME_CONFIG_PAIRS+=("SUGARMAGIC_SUGARPROFILE_SUPABASE_ANON_KEY=${SUGARMAGIC_SUGARPROFILE_SUPABASE_ANON_KEY:-}")
RUNTIME_CONFIG_PAIRS+=("SUGARMAGIC_SUGARPROFILE_SUPABASE_URL=${SUGARMAGIC_SUGARPROFILE_SUPABASE_URL:-}")
RUNTIME_CONFIG_VARS=""
for pair in "${RUNTIME_CONFIG_PAIRS[@]}"; do
  key="${pair%%=*}"
  value="${pair#*=}"
  if [ -n "${value}" ]; then
    # gcloud --set-env-vars="^@^k1=v1@k2=v2" uses @ as the kvpair
    # delimiter (the ^@^ prefix sets it). Join entries with @ here
    # so the parser sees distinct env vars; joining with , would
    # collapse them into a single value (allowed-origins absorbs
    # everything that follows the first comma).
    if [ -z "${RUNTIME_CONFIG_VARS}" ]; then
      RUNTIME_CONFIG_VARS="${pair}"
    else
      RUNTIME_CONFIG_VARS="${RUNTIME_CONFIG_VARS}@${pair}"
    fi
  fi
done

services=(
  "wordlark-v1-1dqlc-sugarmagic-gateway|services/sugarmagic-gateway"
)

if [ ${#services[@]} -eq 0 ]; then
  echo "[sugardeploy] No runtime service units declared by enabled plugins." >&2
  echo "[sugardeploy] Enable a plugin with a runtime service (SugarAgent, etc.) and re-save the project to regenerate this script with services to deploy." >&2
  exit 0
fi

for entry in "${services[@]}"; do
  IFS='|' read -r service_name service_dir <<<"$entry"
  image="${ARTIFACT_REGISTRY_URL}/${service_name}:latest"

  # Story 46.10 — local docker build + push instead of `gcloud builds
  # submit`. The submit path uploads source to Cloud Build's implicit
  # source bucket, which requires the caller (WIF principal on GHA) to
  # hold `serviceusage.services.use` on the project. Building locally
  # sidesteps the whole Cloud Build IAM surface: `gcloud auth
  # configure-docker` already wired docker's credential helper to the
  # active gcloud credentials, so `docker push` just works against
  # Artifact Registry. Faster too (no upload step).
  echo "[sugardeploy] building ${service_name} from ${service_dir}"
  if ! command -v docker >/dev/null 2>&1; then
    echo "[sugardeploy] docker is required to build the gateway image; install Docker (https://docs.docker.com/get-docker/) and retry." >&2
    exit 1
  fi
  docker build -t "${image}" "${service_dir}"

  echo "[sugardeploy] pushing ${service_name} to ${ARTIFACT_REGISTRY_URL}"
  docker push "${image}"

  echo "[sugardeploy] deploying ${service_name}"
  gcloud run deploy "${service_name}" \
    --image "${image}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --service-account "${RUNTIME_SA_EMAIL}" \
    --port=8080 \
    --cpu=1 \
    --memory=512Mi \
    --cpu-throttling \
    --min-instances=1 \
    --max-instances=4 \
    --ingress=all \
    --allow-unauthenticated \
    --set-env-vars="^@^SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS=${ALLOWED_ORIGINS}${RUNTIME_CONFIG_VARS:+@${RUNTIME_CONFIG_VARS}}" \
    "${SECRET_ARGS[@]}"
done
