#!/usr/bin/env bash
# GENERATED BY SUGARMAGIC - DO NOT EDIT
# Re-save the project in Studio to regenerate this file.
# Intentionally NOT using `set -u` (nounset) — macOS ships bash 3.2 which
# treats expanding an empty array (`${arr[@]}`) as "unbound variable" and
# crashes the script before it does anything useful. The critical values
# that would benefit from `-u` (terraform outputs) are explicitly null-
# checked below; that's a stronger guard than `-u` would give us anyway.
set -eo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "[sugardeploy] jq is required to parse terraform outputs; install via brew/apt before running deploy.sh" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="${SCRIPT_DIR}/terraform"

if [ ! -d "${TERRAFORM_DIR}" ]; then
  echo "[sugardeploy] terraform directory not found at ${TERRAFORM_DIR}" >&2
  echo "[sugardeploy] run Setup Infra from the SugarDeploy workspace first" >&2
  exit 1
fi

# Read authoritative deploy-time values from terraform outputs. Terraform
# is the single source of truth for resolved resource names; we don't
# duplicate them here.
TF_OUTPUTS="$(terraform -chdir="${TERRAFORM_DIR}" output -json)"
ARTIFACT_REGISTRY_URL="$(echo "${TF_OUTPUTS}" | jq -r '.artifact_registry_url.value')"
RUNTIME_SA_EMAIL="$(echo "${TF_OUTPUTS}" | jq -r '.runtime_sa_email.value')"
# Story 46.9 — comma-join terraform's allowed_origins list (a JSON
# array) for the gateway env var. Empty list -> empty string, which
# the gateway treats as "no allowed origins" (browsers blocked).
ALLOWED_ORIGINS="$(echo "${TF_OUTPUTS}" | jq -r '.allowed_origins.value | join(",")')"

if [ -z "${ARTIFACT_REGISTRY_URL}" ] || [ "${ARTIFACT_REGISTRY_URL}" = "null" ]; then
  echo "[sugardeploy] terraform output 'artifact_registry_url' is empty; did Setup Infra finish?" >&2
  exit 1
fi
if [ -z "${RUNTIME_SA_EMAIL}" ] || [ "${RUNTIME_SA_EMAIL}" = "null" ]; then
  echo "[sugardeploy] terraform output 'runtime_sa_email' is empty; did Setup Infra finish?" >&2
  exit 1
fi

PROJECT_ID="${SUGARMAGIC_GCP_PROJECT_ID:-wordlark-v1-1dqlc}"
REGION="${SUGARMAGIC_GCP_REGION:-us-central1}"

# Secret bindings: env-var-name → Secret Manager secret id. The actual secret
# values live in Secret Manager (written via the SugarDeploy "Set Value" UI),
# NOT in this script. `--set-secrets` binds them at request time via the
# runtime SA's `roles/secretmanager.secretAccessor` grant (set up by
# terraform). Empty array when no plugin declares secrets.
SECRET_ARGS=(
  "--set-secrets=SUGARMAGIC_ANTHROPIC_API_KEY=wordlark-v1-1dqlc-anthropic-api-key:latest"
  "--set-secrets=SUGARMAGIC_GATEWAY_SHARED_TOKEN=wordlark-v1-1dqlc-gateway-shared-token:latest"
  "--set-secrets=SUGARMAGIC_OPENAI_API_KEY=wordlark-v1-1dqlc-openai-api-key:latest"
)

services=(
  "wordlark-v1-1dqlc-sugarmagic-gateway|services/sugarmagic-gateway"
)

if [ ${#services[@]} -eq 0 ]; then
  echo "[sugardeploy] No runtime service units declared by enabled plugins." >&2
  echo "[sugardeploy] Enable a plugin with a runtime service (SugarAgent, etc.) and re-save the project to regenerate this script with services to deploy." >&2
  exit 0
fi

for entry in "${services[@]}"; do
  IFS='|' read -r service_name service_dir <<<"$entry"
  image="${ARTIFACT_REGISTRY_URL}/${service_name}:latest"

  echo "[sugardeploy] building ${service_name} from ${service_dir}"
  gcloud builds submit "${service_dir}" \
    --tag "${image}" \
    --project "${PROJECT_ID}"

  echo "[sugardeploy] deploying ${service_name}"
  gcloud run deploy "${service_name}" \
    --image "${image}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --service-account "${RUNTIME_SA_EMAIL}" \
    --port=8080 \
    --cpu=1 \
    --memory=512Mi \
    --cpu-throttling \
    --min-instances=1 \
    --max-instances=4 \
    --ingress=all \
    --allow-unauthenticated \
    --set-env-vars="^@^SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS=${ALLOWED_ORIGINS}" \
    "${SECRET_ARGS[@]}"
done
