// GENERATED BY SUGARMAGIC - DO NOT EDIT
// src/deployment/gateway/supabase-jwt.ts
import {
  createHmac,
  createPublicKey,
  timingSafeEqual,
  verify as cryptoVerify
} from "node:crypto";
function decodeBase64Url(segment) {
  const normalized = segment.replace(/-/g, "+").replace(/_/g, "/");
  const padding = normalized.length % 4 === 0 ? 0 : 4 - normalized.length % 4;
  return Buffer.from(normalized + "=".repeat(padding), "base64");
}
var __jwksCache = {
  url: "",
  expiresAt: 0,
  keys: []
};
var __JWKS_TTL_MS = 10 * 60 * 1e3;
async function __fetchJwks(jwksUrl) {
  const now = Date.now();
  if (__jwksCache.url === jwksUrl && __jwksCache.expiresAt > now) {
    return __jwksCache.keys;
  }
  let response;
  try {
    response = await fetch(jwksUrl);
  } catch (error) {
    console.error("[sugardeploy] supabase-jwt:jwks-fetch-failed " + JSON.stringify({
      jwksUrl,
      error: error instanceof Error ? error.message : String(error)
    }));
    return null;
  }
  if (!response.ok) {
    console.error("[sugardeploy] supabase-jwt:jwks-non-2xx " + JSON.stringify({
      jwksUrl,
      status: response.status
    }));
    return null;
  }
  let body;
  try {
    body = await response.json();
  } catch (error) {
    console.error("[sugardeploy] supabase-jwt:jwks-bad-json " + JSON.stringify({
      jwksUrl,
      error: error instanceof Error ? error.message : String(error)
    }));
    return null;
  }
  const keys = Array.isArray(body && body.keys) ? body.keys : [];
  __jwksCache.url = jwksUrl;
  __jwksCache.expiresAt = now + __JWKS_TTL_MS;
  __jwksCache.keys = keys;
  return keys;
}
function __jwsSigToDer(rawSig) {
  if (rawSig.length !== 64) return null;
  const r = rawSig.subarray(0, 32);
  const s = rawSig.subarray(32);
  function trim(buf) {
    let i = 0;
    while (i < buf.length - 1 && buf[i] === 0) i++;
    let trimmed = buf.subarray(i);
    if (trimmed[0] & 128) {
      trimmed = Buffer.concat([Buffer.from([0]), trimmed]);
    }
    return trimmed;
  }
  const rTrimmed = trim(r);
  const sTrimmed = trim(s);
  const seqBody = Buffer.concat([
    Buffer.from([2, rTrimmed.length]),
    rTrimmed,
    Buffer.from([2, sTrimmed.length]),
    sTrimmed
  ]);
  return Buffer.concat([Buffer.from([48, seqBody.length]), seqBody]);
}
async function verifySupabaseJwt(req) {
  const supabaseUrl = (process.env["SUGARMAGIC_SUGARPROFILE_SUPABASE_URL"] || "").trim();
  if (!supabaseUrl) return null;
  const jwksUrl = supabaseUrl.replace(/\/+$/, "") + "/auth/v1/.well-known/jwks.json";
  const authHeader = req.headers && req.headers["authorization"] || "";
  const prefix = "Bearer ";
  if (typeof authHeader !== "string" || !authHeader.startsWith(prefix)) return null;
  const token = authHeader.slice(prefix.length).trim();
  if (!token) return null;
  const parts = token.split(".");
  if (parts.length !== 3) return null;
  const [headerB64, payloadB64, signatureB64] = parts;
  let jwtHeader;
  try {
    jwtHeader = JSON.parse(decodeBase64Url(headerB64).toString("utf8"));
  } catch {
    return null;
  }
  if (!jwtHeader || typeof jwtHeader !== "object") return null;
  const alg = jwtHeader["alg"];
  const kid = jwtHeader["kid"];
  if (typeof alg !== "string" || typeof kid !== "string" || !kid) return null;
  if (alg !== "ES256" && alg !== "HS256") return null;
  const keys = await __fetchJwks(jwksUrl);
  if (!keys) return null;
  const jwk = keys.find((entry) => entry && entry["kid"] === kid);
  if (!jwk) return null;
  if (jwk["alg"] && jwk["alg"] !== alg) return null;
  let signature;
  try {
    signature = decodeBase64Url(signatureB64);
  } catch {
    return null;
  }
  const signingInput = Buffer.from(headerB64 + "." + payloadB64, "utf8");
  if (alg === "ES256") {
    if (jwk["kty"] !== "EC" || jwk["crv"] !== "P-256") return null;
    let publicKey;
    try {
      publicKey = createPublicKey({ key: jwk, format: "jwk" });
    } catch (error) {
      console.error("[sugardeploy] supabase-jwt:jwk-import-failed " + JSON.stringify({
        kid,
        error: error instanceof Error ? error.message : String(error)
      }));
      return null;
    }
    const derSig = __jwsSigToDer(signature);
    if (!derSig) return null;
    let valid;
    try {
      valid = cryptoVerify("SHA256", signingInput, publicKey, derSig);
    } catch {
      return null;
    }
    if (!valid) return null;
  } else {
    if (jwk["kty"] !== "oct" || typeof jwk["k"] !== "string") return null;
    let secretBytes;
    try {
      secretBytes = decodeBase64Url(jwk["k"]);
    } catch {
      return null;
    }
    const expectedSig = createHmac("sha256", secretBytes).update(signingInput).digest();
    if (expectedSig.length !== signature.length) return null;
    try {
      if (!timingSafeEqual(expectedSig, signature)) return null;
    } catch {
      return null;
    }
  }
  let payload;
  try {
    payload = JSON.parse(decodeBase64Url(payloadB64).toString("utf8"));
  } catch {
    return null;
  }
  if (payload === null || typeof payload !== "object") return null;
  if (payload["aud"] !== "authenticated") return null;
  const nowSeconds = Math.floor(Date.now() / 1e3);
  if (typeof payload["exp"] !== "number" || payload["exp"] <= nowSeconds) return null;
  if (typeof payload["sub"] !== "string" || !payload["sub"]) return null;
  return {
    userId: payload["sub"],
    email: typeof payload["email"] === "string" ? payload["email"] : null
  };
}

// src/deployment/gateway/lore-designation.ts
var PERSONA_CARD_SECTION_SLUGS = ["persona", "voice"];
var SECRETS_SECTION_SLUG = "secrets";
var RELATIONSHIPS_SECTION_SLUG = "relationships";
var RECOVERY_SECTION_SLUG = "recovery";
var RECOVERY_STRATEGIES = [
  "curt-exit",
  "change-subject",
  "joke",
  "playful-probe",
  "self-disclosure",
  "gossip"
];
function isPersonaCardSection(section) {
  return PERSONA_CARD_SECTION_SLUGS.includes(section.slug);
}
function isRelationshipsSection(section) {
  return section.slug === RELATIONSHIPS_SECTION_SLUG;
}
function isRecoverySection(section) {
  return section.slug === RECOVERY_SECTION_SLUG;
}
function isWithheldSection(section) {
  return isSecretSection(section) || isRecoverySection(section);
}
var LINKED_NAME = /^(?:[-*]\s+)?\[([^\]]+)\]\(([^)]+)\)\s*(.*)$/;
function stripLeadingSeparator(text) {
  return text.replace(/^(--|\u2014|:)\s*/, "").trim();
}
function parseRelationshipEntries(content) {
  const entries = [];
  for (const rawLine of content.split("\n")) {
    const line = rawLine.trim();
    if (line.length === 0) continue;
    const linked = LINKED_NAME.exec(line);
    if (linked) {
      entries.push({
        name: linked[1].trim(),
        pageId: linked[2].trim() || null,
        description: stripLeadingSeparator(linked[3] ?? "")
      });
      continue;
    }
    const previous = entries[entries.length - 1];
    if (previous) {
      previous.description = previous.description ? `${previous.description} ${line}` : line;
    }
  }
  return entries;
}
function findRelationshipEntry(entries, target) {
  const pageId = target.pageId?.trim() ?? "";
  const title = target.title?.trim().toLowerCase() ?? "";
  for (const entry of entries) {
    if (pageId && entry.pageId === pageId) return entry;
    if (title && entry.name.trim().toLowerCase() === title) return entry;
  }
  return null;
}
function isSecretSection(section) {
  return section.slug === SECRETS_SECTION_SLUG;
}
var RECOVERY_ENTRY = /^[-*]\s+([^\s:]+)/;
function isRecoveryStrategy(name) {
  return RECOVERY_STRATEGIES.includes(name);
}
function parseRecoveryStrategies(content) {
  const strategies = [];
  const unrecognized = [];
  for (const rawLine of content.split("\n")) {
    const entry = RECOVERY_ENTRY.exec(rawLine.trim());
    if (!entry) continue;
    const name = entry[1].toLowerCase();
    if (isRecoveryStrategy(name)) {
      strategies.push(name);
    } else {
      unrecognized.push(name);
    }
  }
  return { strategies, unrecognized };
}
function designateLoreSections(sections) {
  const personaCard = [];
  const coreKnowledge = [];
  const secrets = [];
  const recovery = [];
  for (const section of sections) {
    if (isSecretSection(section)) {
      secrets.push(section);
    } else if (isRecoverySection(section)) {
      recovery.push(section);
    } else if (isPersonaCardSection(section)) {
      personaCard.push(section);
    } else {
      coreKnowledge.push(section);
    }
  }
  return { personaCard, coreKnowledge, secrets, recovery };
}
function composeLoreBody(sections) {
  return sections.map(
    (section) => (
      // The implicit pre-heading section (slug "overview") had no heading in
      // the source, so re-emit its content only -- don't inject a synthetic
      // "## Overview" the author never wrote.
      section.slug === "overview" ? section.content : `## ${section.heading}

${section.content}`
    )
  ).join("\n\n");
}

// src/deployment/gateway/core.ts
import { createServer } from "node:http";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, extname, join, relative } from "node:path";
import {
  createHash,
  timingSafeEqual as timingSafeEqual2
} from "node:crypto";
var SOFT_PAGE_CHUNK_SLUG = "_page";
var GATEWAY_DEFAULT_SCORE_THRESHOLD = 0.3;
var _routes = [];
var _serviceUnitId = "";
var _targetId = "";
var _loreIngestState = {
  active: false,
  phase: "idle",
  pageCount: 0,
  chunkCount: 0,
  uploadedCount: 0,
  currentChunkId: null,
  message: "Idle",
  warnings: [],
  startedAt: null,
  completedAt: null
};
var _allowedOriginPatterns = [];
function initGateway(manifest) {
  _routes = manifest.routes ?? [];
  _serviceUnitId = manifest.serviceUnitId ?? "";
  _targetId = manifest.targetId ?? "";
  _allowedOriginPatterns = (process.env["SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS"] ?? "").split(",").map((entry) => entry.trim()).filter((entry) => entry.length > 0);
}
function resetLoreIngestState() {
  Object.assign(_loreIngestState, {
    active: false,
    phase: "idle",
    pageCount: 0,
    chunkCount: 0,
    uploadedCount: 0,
    currentChunkId: null,
    message: "Idle",
    warnings: [],
    startedAt: null,
    completedAt: null
  });
}
function resolveAllowedOrigin(origin) {
  if (!origin) return null;
  for (const pattern of _allowedOriginPatterns) {
    if (pattern === origin) return origin;
    const wildcardIndex = pattern.indexOf("*");
    if (wildcardIndex >= 0) {
      const prefix = pattern.slice(0, wildcardIndex);
      const suffix = pattern.slice(wildcardIndex + 1);
      if (origin.length >= prefix.length + suffix.length && origin.startsWith(prefix) && origin.endsWith(suffix)) {
        return origin;
      }
    }
  }
  return null;
}
var _baseHeaders = {
  "content-type": "application/json; charset=utf-8"
};
function resolveCorsHeaders(req) {
  const headers = { vary: "origin" };
  const origin = req?.headers?.origin;
  const echoOrigin = resolveAllowedOrigin(origin);
  if (echoOrigin) {
    headers["access-control-allow-origin"] = echoOrigin;
    headers["access-control-allow-credentials"] = "true";
  }
  return headers;
}
function sendJson(res, statusCode, payload) {
  res.writeHead(statusCode, {
    ..._baseHeaders,
    ...res.__sugarmagicCors ?? {}
  });
  res.end(JSON.stringify(payload, null, 2));
}
function logInfo(message, payload) {
  const suffix = payload && typeof payload === "object" ? " " + JSON.stringify(payload) : payload != null ? " " + String(payload) : "";
  console.log("[sugardeploy] " + message + suffix);
}
function callerUserId(req) {
  const user = req.user;
  return typeof user?.userId === "string" ? user.userId : null;
}
function logModelUsage(usage) {
  setImmediate(() => {
    try {
      process.stdout.write(
        JSON.stringify({
          kind: "gateway.model-usage",
          timestamp: Date.now(),
          ...usage
        }) + "\n"
      );
    } catch {
    }
  });
}
function logError(message, error, payload) {
  const details = {
    ...payload && typeof payload === "object" ? payload : {},
    error: error instanceof Error ? error.message : String(error)
  };
  console.error("[sugardeploy] " + message + " " + JSON.stringify(details));
}
function updateLoreIngestState(patch) {
  Object.assign(_loreIngestState, patch);
}
function sendMethodNotAllowed(res, allowed) {
  res.writeHead(405, {
    ..._baseHeaders,
    ...res.__sugarmagicCors ?? {},
    allow: allowed.join(", ")
  });
  res.end(
    JSON.stringify(
      {
        ok: false,
        error: "MethodNotAllowed",
        allowed
      },
      null,
      2
    )
  );
}
function normalizePath(url) {
  return (url || "/").split("?")[0] || "/";
}
function authorizeBearer(req) {
  const expected = process.env["SUGARMAGIC_GATEWAY_SHARED_TOKEN"] || "";
  if (!expected) return false;
  const header = req.headers && req.headers["authorization"] || "";
  const prefix = "Bearer ";
  if (typeof header !== "string" || !header.startsWith(prefix)) return false;
  const presented = header.slice(prefix.length).trim();
  if (!presented) return false;
  const expectedBuf = Buffer.from(expected, "utf8");
  const presentedBuf = Buffer.from(presented, "utf8");
  if (expectedBuf.length !== presentedBuf.length) return false;
  try {
    return timingSafeEqual2(expectedBuf, presentedBuf);
  } catch {
    return false;
  }
}
function resolveEnv(name, fallback = "") {
  const value = process.env[name];
  return typeof value === "string" ? value.trim() || fallback : fallback;
}
function requireEnv(name) {
  const value = resolveEnv(name);
  if (!value) {
    throw new Error("Missing required environment variable: " + name);
  }
  return value;
}
async function readJsonBody(req) {
  let requestBody = "";
  for await (const chunk of req) {
    requestBody += chunk.toString();
  }
  if (!requestBody.trim()) {
    return {};
  }
  try {
    return JSON.parse(requestBody);
  } catch {
    throw new Error("Request body must be valid JSON.");
  }
}
async function parseApiJsonResponse(response, label) {
  const raw = await response.text();
  let payload = null;
  if (raw.trim()) {
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }
  }
  if (!response.ok) {
    throw new Error(
      label + " failed with status " + response.status + (raw.trim() ? ": " + raw : "")
    );
  }
  return payload;
}
async function requestJson(url, options, label) {
  logInfo("upstream:request", {
    label,
    url,
    method: options?.method ?? "GET"
  });
  const response = await fetch(url, options);
  const raw = await response.text();
  let payload = null;
  if (raw.trim()) {
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }
  }
  if (!response.ok) {
    logError(label + " failed", new Error("upstream non-2xx"), {
      url,
      status: response.status,
      body: raw
    });
    throw new Error(
      label + " failed with status " + response.status + (typeof payload === "string" ? ": " + payload : payload && typeof payload === "object" && "error" in payload ? ": " + JSON.stringify(payload) : "")
    );
  }
  return {
    payload,
    headers: response.headers
  };
}
var UNSUPPORTED_SCHEMA_KEYWORDS = /* @__PURE__ */ new Set([
  "minimum",
  "maximum",
  "exclusiveMinimum",
  "exclusiveMaximum",
  "multipleOf",
  "minLength",
  "maxLength",
  "pattern",
  "minItems",
  "maxItems",
  "uniqueItems",
  "minProperties",
  "maxProperties"
]);
var SCHEMA_NAME_MAPS = /* @__PURE__ */ new Set(["properties", "$defs", "definitions"]);
function sanitizeSchemaNode(node) {
  if (Array.isArray(node)) {
    return node.map(sanitizeSchemaNode);
  }
  if (!node || typeof node !== "object") {
    return node;
  }
  const result = {};
  for (const [key, value] of Object.entries(node)) {
    if (UNSUPPORTED_SCHEMA_KEYWORDS.has(key)) {
      continue;
    }
    if (SCHEMA_NAME_MAPS.has(key) && value && typeof value === "object") {
      const mapped = {};
      for (const [name, child] of Object.entries(value)) {
        mapped[name] = sanitizeSchemaNode(child);
      }
      result[key] = mapped;
      continue;
    }
    result[key] = sanitizeSchemaNode(value);
  }
  if (result["type"] === "object" || result["properties"] !== void 0) {
    result["additionalProperties"] = false;
  }
  return result;
}
function toStructuredOutputSchema(schema) {
  if (!schema || typeof schema !== "object" || Array.isArray(schema)) {
    return null;
  }
  const sanitized = sanitizeSchemaNode(schema);
  if (!sanitized || typeof sanitized !== "object") {
    return null;
  }
  return sanitized;
}
function slugify(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "section";
}
function sanitizeFilename(value) {
  return value.replace(/[^a-z0-9._-]+/gi, "-").replace(/-+/g, "-");
}
function parseFrontmatter(raw) {
  if (!raw.startsWith("---\n")) {
    return {
      metadata: {},
      body: raw
    };
  }
  const closingIndex = raw.indexOf("\n---\n", 4);
  if (closingIndex === -1) {
    return {
      metadata: {},
      body: raw
    };
  }
  const frontmatter = raw.slice(4, closingIndex);
  const body = raw.slice(closingIndex + 5);
  const metadata = {};
  for (const line of frontmatter.split("\n")) {
    const separatorIndex = line.indexOf(":");
    if (separatorIndex === -1) continue;
    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    if (!key) continue;
    metadata[key] = value.replace(/^['"]|['"]$/g, "");
  }
  return {
    metadata,
    body
  };
}
function readCanonLevel(metadata, relativePath, warnings) {
  const raw = (metadata["canon_level"] ?? "").trim().toLowerCase();
  if (!raw) return "hard";
  if (raw === "hard" || raw === "soft") return raw;
  warnings.push(
    "Lore page " + relativePath + ' has canon_level "' + raw + '", which is not hard or soft. Indexed as hard.'
  );
  return "hard";
}
function stripTrailingRule(content) {
  return content.replace(/(?:\n\s*(?:-{3,}|\*{3,}|_{3,})\s*)+$/, "").trim();
}
function splitLoreSections(markdown) {
  const lines = markdown.split("\n");
  const sections = [];
  let current = {
    heading: "Overview",
    slug: "overview",
    contentLines: []
  };
  for (const line of lines) {
    const headingMatch = /^(#{1,6})\s+(.+)$/.exec(line.trim());
    if (headingMatch) {
      const content = stripTrailingRule(current.contentLines.join("\n"));
      if (content) {
        sections.push({
          heading: current.heading,
          slug: current.slug,
          content
        });
      }
      const heading = headingMatch[2].trim();
      current = {
        heading,
        slug: slugify(heading),
        contentLines: []
      };
      continue;
    }
    current.contentLines.push(line);
  }
  const trailingContent = stripTrailingRule(current.contentLines.join("\n"));
  if (trailingContent) {
    sections.push({
      heading: current.heading,
      slug: current.slug,
      content: trailingContent
    });
  }
  return sections.length > 0 ? sections : [
    {
      heading: "Overview",
      slug: "overview",
      content: markdown.trim()
    }
  ];
}
function walkMarkdownFiles(rootDir, currentDir = rootDir, files = []) {
  for (const entry of readdirSync(currentDir, { withFileTypes: true })) {
    const absolutePath = join(currentDir, entry.name);
    if (entry.isDirectory()) {
      walkMarkdownFiles(rootDir, absolutePath, files);
      continue;
    }
    const extension = extname(entry.name).toLowerCase();
    if (extension === ".md" || extension === ".markdown") {
      files.push(absolutePath);
    }
  }
  return files;
}
function resolveLoreSource() {
  const sourceKind = resolveEnv("SUGARMAGIC_LORE_SOURCE_KIND", "local");
  const sourcePath = resolveEnv("SUGARMAGIC_LORE_SOURCE_PATH");
  const repositoryUrl = resolveEnv("SUGARMAGIC_LORE_SOURCE_REPOSITORY_URL");
  const repositoryRef = resolveEnv("SUGARMAGIC_LORE_SOURCE_REPOSITORY_REF", "main");
  if (sourceKind === "github") {
    return {
      sourceKind,
      sourcePath: null,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning: "GitHub-backed lore source resolution is planned but not implemented yet. Use a local checked-out lore repo for now."
    };
  }
  if (!sourcePath) {
    return {
      sourceKind: "local",
      sourcePath: null,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning: "SUGARMAGIC_LORE_SOURCE_PATH is not configured in the gateway environment."
    };
  }
  try {
    const stats = statSync(sourcePath);
    if (!stats.isDirectory()) {
      return {
        sourceKind: "local",
        sourcePath,
        repositoryUrl,
        repositoryRef,
        sourceReady: false,
        warning: "Configured lore source path is not a directory: " + sourcePath
      };
    }
  } catch (error) {
    return {
      sourceKind: "local",
      sourcePath,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning: "Configured lore source path is not readable: " + sourcePath + " (" + (error instanceof Error ? error.message : String(error)) + ")"
    };
  }
  return {
    sourceKind: "local",
    sourcePath,
    repositoryUrl,
    repositoryRef,
    sourceReady: true,
    warning: null
  };
}
function readLorePages() {
  const source = resolveLoreSource();
  if (!source.sourceReady || !source.sourcePath) {
    return {
      source,
      pages: [],
      chunks: [],
      warnings: source.warning ? [source.warning] : []
    };
  }
  const warnings = source.warning ? [source.warning] : [];
  const pages = [];
  const chunks = [];
  const markdownFiles = walkMarkdownFiles(source.sourcePath);
  for (const absolutePath of markdownFiles) {
    const raw = readFileSync(absolutePath, "utf8");
    const { metadata, body } = parseFrontmatter(raw);
    const pageId = typeof metadata["id"] === "string" ? metadata["id"].trim() : "";
    if (!pageId) {
      warnings.push(
        "Skipped lore page without frontmatter id: " + relative(source.sourcePath, absolutePath)
      );
      continue;
    }
    const relativePath = relative(source.sourcePath, absolutePath);
    const title = typeof metadata["title"] === "string" && metadata["title"].trim() || pageId.split(".").at(-1) || pageId;
    const sections = splitLoreSections(body);
    for (const section of sections.filter(isRecoverySection)) {
      for (const name of parseRecoveryStrategies(section.content).unrecognized) {
        warnings.push(
          'Ignored unknown recovery strategy "' + name + '" in ' + relativePath + " (" + pageId + "). Known strategies: " + RECOVERY_STRATEGIES.join(", ") + "."
        );
      }
    }
    pages.push({
      pageId,
      title,
      relativePath,
      sectionCount: sections.length,
      body,
      sections
    });
    const canonLevel = readCanonLevel(metadata, relativePath, warnings);
    if (canonLevel === "soft") {
      chunks.push({
        pageId,
        chunkId: pageId + "#" + SOFT_PAGE_CHUNK_SLUG,
        title,
        sectionHeading: title,
        sectionSlug: SOFT_PAGE_CHUNK_SLUG,
        relativePath,
        embeddingText: ["Page ID: " + pageId, "Title: " + title].join("\n\n"),
        canonLevel
      });
      continue;
    }
    for (const section of sections) {
      if (isWithheldSection(section)) continue;
      const chunkId = pageId + "#" + section.slug;
      const embeddingText = [
        "Page ID: " + pageId,
        "Title: " + title,
        "Section: " + section.heading,
        section.content
      ].filter(Boolean).join("\n\n");
      chunks.push({
        pageId,
        chunkId,
        title,
        sectionHeading: section.heading,
        sectionSlug: section.slug,
        relativePath,
        embeddingText,
        canonLevel
      });
    }
  }
  pages.sort((left, right) => left.pageId.localeCompare(right.pageId));
  chunks.sort((left, right) => left.chunkId.localeCompare(right.chunkId));
  return {
    source,
    pages,
    chunks,
    warnings
  };
}
async function withOpenAIRetry(label, fn, maxAttempts = 3) {
  let lastError;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;
      const isTransient = error instanceof Error && /status (?:429|50[234])/.test(error.message);
      if (!isTransient || attempt === maxAttempts - 1) throw error;
      const delayMs = 1e3 * (attempt + 1);
      logInfo("upstream:retry", { label, attempt: attempt + 1, delayMs });
      await new Promise((r) => setTimeout(r, delayMs));
    }
  }
  throw lastError;
}
async function listVectorStoreFiles(vectorStoreId) {
  const items = [];
  let after = "";
  while (true) {
    const query = after ? "?after=" + encodeURIComponent(after) : "";
    const { payload } = await requestJson(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files" + query,
      {
        method: "GET",
        headers: {
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        }
      },
      "OpenAI vector store file list"
    );
    const batch = Array.isArray(payload?.data) ? payload.data : [];
    items.push(...batch);
    if (!payload?.has_more || batch.length === 0) {
      break;
    }
    after = typeof batch[batch.length - 1]?.["id"] === "string" ? batch[batch.length - 1]["id"] : "";
    if (!after) break;
  }
  return items;
}
function isLoreVectorStoreFile(item) {
  const attributes = item["attributes"];
  if (typeof attributes !== "object" || attributes === null) return false;
  const pageId = attributes["page_id"];
  return typeof pageId === "string" && pageId.length > 0;
}
async function sweepNonLoreVectorStoreFiles(vectorStoreId) {
  const files = await listVectorStoreFiles(vectorStoreId);
  const removed = [];
  let failed = 0;
  for (const item of files) {
    const id = item["id"];
    if (typeof id !== "string" || isLoreVectorStoreFile(item)) continue;
    try {
      await deleteVectorStoreFile(vectorStoreId, id);
      removed.push(id);
    } catch {
      failed += 1;
    }
  }
  return { removed, failed };
}
async function deleteVectorStoreFile(vectorStoreId, vectorStoreFileId) {
  await requestJson(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + vectorStoreFileId,
    {
      method: "DELETE",
      headers: {
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      }
    },
    "OpenAI vector store file delete"
  );
}
var MAX_FILES_PER_BATCH = 2e3;
var UPLOAD_CONCURRENCY = 8;
var BATCH_INDEX_DEADLINE_MS = 30 * 60 * 1e3;
var BATCH_POLL_INTERVAL_MS = 2e3;
function chunkContentHash(chunk) {
  return createHash("sha256").update(chunk.embeddingText, "utf8").digest("hex");
}
function chunkAttributes(chunk) {
  return {
    page_id: chunk.pageId,
    chunk_id: chunk.chunkId,
    section_slug: chunk.sectionSlug,
    section_heading: chunk.sectionHeading,
    title: chunk.title,
    relative_path: chunk.relativePath,
    canon_level: chunk.canonLevel,
    content_hash: chunkContentHash(chunk)
  };
}
function indexedChunksByAddress(files) {
  const byAddress = /* @__PURE__ */ new Map();
  for (const file of files) {
    if (!isLoreVectorStoreFile(file)) continue;
    const id = file["id"];
    const attributes = file["attributes"];
    const chunkId = attributes["chunk_id"];
    if (typeof id !== "string" || typeof chunkId !== "string") continue;
    const hash = attributes["content_hash"];
    const status = file["status"];
    const entry = {
      fileId: id,
      contentHash: typeof hash === "string" ? hash : "",
      status: typeof status === "string" ? status : "unknown"
    };
    byAddress.set(chunkId, [...byAddress.get(chunkId) ?? [], entry]);
  }
  return byAddress;
}
function planIncrementalIngest(chunks, indexed) {
  const upload = [];
  const unchanged = [];
  const remove = [];
  const duplicateAddresses = [];
  const seen = /* @__PURE__ */ new Set();
  for (const chunk of chunks) {
    if (seen.has(chunk.chunkId)) {
      duplicateAddresses.push(chunk.chunkId);
      continue;
    }
    seen.add(chunk.chunkId);
    const entries = indexed.get(chunk.chunkId) ?? [];
    const hash = chunkContentHash(chunk);
    const usable = entries.filter(
      (entry) => entry.status === "completed" && entry.contentHash === hash
    );
    if (usable.length > 0) {
      unchanged.push(chunk);
      const keep = usable[0].fileId;
      for (const entry of entries) {
        if (entry.fileId !== keep) remove.push(entry.fileId);
      }
    } else {
      upload.push(chunk);
      for (const entry of entries) remove.push(entry.fileId);
    }
  }
  for (const [chunkId, entries] of indexed) {
    if (seen.has(chunkId)) continue;
    for (const entry of entries) remove.push(entry.fileId);
  }
  return { upload, unchanged, remove, duplicateAddresses };
}
async function uploadChunkFile(chunk) {
  const fileUpload = new FormData();
  fileUpload.append("purpose", "user_data");
  fileUpload.append(
    "file",
    new Blob([chunk.embeddingText], { type: "text/markdown" }),
    sanitizeFilename(chunk.chunkId) + ".md"
  );
  const uploadResponse = await fetch("https://api.openai.com/v1/files", {
    method: "POST",
    headers: {
      authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
    },
    body: fileUpload
  });
  const payload = await parseApiJsonResponse(
    uploadResponse,
    "OpenAI file upload"
  );
  const fileId = payload["id"];
  if (typeof fileId !== "string") {
    throw new Error("OpenAI file upload returned no id for chunk " + chunk.chunkId);
  }
  return fileId;
}
async function mapWithConcurrency(items, limit, worker) {
  const results = new Array(items.length);
  let next = 0;
  let aborted = false;
  async function runner() {
    while (!aborted) {
      const index = next;
      next += 1;
      if (index >= items.length) return;
      try {
        results[index] = await worker(items[index], index);
      } catch (error) {
        aborted = true;
        throw error;
      }
    }
  }
  await Promise.all(
    Array.from({ length: Math.max(1, Math.min(limit, items.length)) }, runner)
  );
  return results;
}
async function attachChunkBatch(vectorStoreId, entries, onProgress = null) {
  const batchId = await withOpenAIRetry("attach-batch-create", async () => {
    const createResponse = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/file_batches",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        },
        body: JSON.stringify({
          files: entries.map((entry) => ({
            file_id: entry.fileId,
            attributes: chunkAttributes(entry.chunk)
          }))
        })
      }
    );
    const batch = await parseApiJsonResponse(
      createResponse,
      "OpenAI vector store file batch create"
    );
    const id = batch["id"];
    if (typeof id !== "string") {
      throw new Error("OpenAI file batch create returned no id.");
    }
    return id;
  });
  const deadline = Date.now() + BATCH_INDEX_DEADLINE_MS;
  while (Date.now() < deadline) {
    let payload;
    try {
      const statusResponse = await fetch(
        "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/file_batches/" + batchId,
        {
          method: "GET",
          headers: {
            authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
          }
        }
      );
      payload = await parseApiJsonResponse(
        statusResponse,
        "OpenAI vector store file batch status"
      );
    } catch (error) {
      logInfo("ingest:batch-status-retry", {
        batchId,
        reason: error instanceof Error ? error.message : String(error)
      });
      await new Promise((resolve) => setTimeout(resolve, BATCH_POLL_INTERVAL_MS));
      continue;
    }
    const counts = payload["file_counts"] ?? {};
    const completed = typeof counts["completed"] === "number" ? counts["completed"] : 0;
    const failed = typeof counts["failed"] === "number" ? counts["failed"] : 0;
    onProgress?.(completed, entries.length);
    const status = payload["status"];
    if (status === "completed" || status === "failed" || status === "cancelled") {
      if (status !== "completed" || failed > 0) {
        throw new Error(
          "Vector store file batch " + String(status) + ": " + completed + " indexed, " + failed + " failed of " + entries.length + " files."
        );
      }
      return completed;
    }
    await new Promise((resolve) => setTimeout(resolve, BATCH_POLL_INTERVAL_MS));
  }
  throw new Error(
    "Timed out waiting for vector store batch indexing after " + Math.round(BATCH_INDEX_DEADLINE_MS / 6e4) + " minutes."
  );
}
function findManagedRoute(path) {
  return _routes.find(
    (route) => path === route.path || path.startsWith(route.path + "/")
  );
}
async function handleSugarAgentGenerate(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const body = await readJsonBody(req);
  const purpose = typeof body["purpose"] === "string" ? body["purpose"].trim() : "";
  const dialogueModel = () => resolveEnv("SUGARMAGIC_SUGARAGENT_ANTHROPIC_MODEL", "claude-haiku-4-5");
  const PURPOSE_MODELS = {
    // sugaragent: the cheap end-of-conversation memory pass.
    summary: () => resolveEnv("SUGARMAGIC_SUGARAGENT_SUMMARY_MODEL", "claude-haiku-4-5"),
    // sugaragent: regenerating a reply that failed the judge.
    regen: () => resolveEnv("SUGARMAGIC_SUGARAGENT_REGEN_MODEL", dialogueModel()),
    // sugarlang: the Teacher's pedagogical judgment call. Deliberately its own
    // env var — this is the most reasoning-heavy call in the product and must
    // not silently ride the cheap dialogue model (which it did until 2026-07-28).
    teacher: () => resolveEnv("SUGARMAGIC_SUGARLANG_TEACHER_MODEL", "claude-sonnet-4-6"),
    // sugarlang: COMPILE-time extraction over authored content — multi-word
    // expressions, line intent, and scene concepts. Authoring-time and cached
    // by content hash, so it is paid once per content change rather than per
    // turn; that budget buys a stronger model than the dialogue default.
    //
    // MUST SUPPORT STRUCTURED OUTPUTS. Extraction sends a schema so the reply
    // cannot be unparseable JSON, and a model without that support ignores the
    // schema and puts the pass back to repairing whatever it gets. Sonnet 4.6,
    // the previous default, is not on that list.
    extraction: () => resolveEnv("SUGARMAGIC_SUGARLANG_EXTRACTION_MODEL", "claude-sonnet-5")
  };
  const model = (PURPOSE_MODELS[purpose] ?? dialogueModel)();
  logInfo("sugaragent.generate", { purpose: purpose || "dialogue", model });
  const systemPrompt = typeof body["systemPrompt"] === "string" ? body["systemPrompt"].trim() : "";
  const userPrompt = typeof body["userPrompt"] === "string" ? body["userPrompt"].trim() : "";
  const maxTokens = typeof body["maxTokens"] === "number" && Number.isFinite(body["maxTokens"]) ? Math.max(1, Math.floor(body["maxTokens"])) : 300;
  const rawSystemBlocks = Array.isArray(body["systemBlocks"]) ? body["systemBlocks"] : null;
  const systemBlocks = rawSystemBlocks ? rawSystemBlocks.filter(
    (entry) => !!entry && typeof entry === "object" && typeof entry.text === "string" && entry.text.trim().length > 0
  ).map((entry) => ({
    text: entry.text.trim(),
    cache: entry.cache === true
  })) : null;
  const hasSystemBlocks = !!systemBlocks && systemBlocks.length > 0;
  if (!systemPrompt && !hasSystemBlocks || !userPrompt) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "userPrompt and one of systemPrompt or systemBlocks are required."
    });
    return;
  }
  {
    const blocklistRaw = resolveEnv("SUGARMAGIC_SUGARAGENT_BLOCKLIST", "");
    if (blocklistRaw) {
      const blockTerms = blocklistRaw.split(",").map((t) => t.trim().toLowerCase()).filter(Boolean);
      const loweredPrompt = userPrompt.toLowerCase();
      const blockHit = blockTerms.find((t) => loweredPrompt.includes(t));
      if (blockHit) {
        logInfo("sugaragent.generate-blocklist-hit", { term: blockHit });
        sendJson(res, 200, {
          text: "I'm not sure I can help with that right now.",
          requestId: null,
          usage: { inputTokens: 0, outputTokens: 0, cacheReadInputTokens: 0, cacheCreationInputTokens: 0 },
          model: "deterministic"
        });
        return;
      }
    }
  }
  const anthropicSystem = hasSystemBlocks ? systemBlocks.map((block) => ({
    type: "text",
    text: block.text,
    ...block.cache ? { cache_control: { type: "ephemeral" } } : {}
  })) : systemPrompt;
  const outputSchema = toStructuredOutputSchema(body["outputSchema"]);
  if (outputSchema) {
    logInfo("sugaragent.generate-structured-output", { purpose: purpose || "dialogue", model });
  }
  const generateStartedAt = Date.now();
  const { payload, headers } = await requestJson(
    "https://api.anthropic.com/v1/messages",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": requireEnv("SUGARMAGIC_ANTHROPIC_API_KEY"),
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model,
        max_tokens: maxTokens,
        system: anthropicSystem,
        messages: [
          {
            role: "user",
            content: userPrompt
          }
        ],
        ...outputSchema ? {
          output_config: {
            format: { type: "json_schema", schema: outputSchema }
          },
          thinking: { type: "disabled" }
        } : {}
      })
    },
    "Anthropic request"
  );
  const text = Array.isArray(payload?.content) ? payload.content.filter((block) => block?.type === "text" && typeof block.text === "string").map((block) => block.text.trim()).filter(Boolean).join("\n\n") : "";
  if (!text) {
    throw new Error("Anthropic response did not include text content.");
  }
  const rawUsage = payload.usage ?? {};
  const usageNumber = (key) => {
    const value = rawUsage[key];
    return typeof value === "number" && Number.isFinite(value) ? value : 0;
  };
  const servedModel = typeof payload.model === "string" && payload.model.trim().length > 0 ? payload.model : model;
  logModelUsage({
    vendor: "anthropic",
    purpose: purpose || "generate",
    model: servedModel,
    userId: callerUserId(req),
    latencyMs: Date.now() - generateStartedAt,
    ok: true,
    inputTokens: usageNumber("input_tokens"),
    outputTokens: usageNumber("output_tokens"),
    cacheReadInputTokens: usageNumber("cache_read_input_tokens"),
    cacheCreationInputTokens: usageNumber("cache_creation_input_tokens")
  });
  sendJson(res, 200, {
    text,
    requestId: headers.get("request-id"),
    // WHY THE MODEL STOPPED. A reply cut off at `max_tokens` and a reply the
    // model simply wrote badly are indistinguishable from the text alone: both
    // arrive as something that will not parse. The scene-context pass failed
    // for days reported as "invalid JSON" when every one of those replies was
    // complete-but-truncated, and the parser error was the only clue anyone
    // had. Callers branch on this instead of guessing from a parser message.
    stopReason: typeof payload.stop_reason === "string" ? payload.stop_reason : null,
    usage: {
      inputTokens: usageNumber("input_tokens"),
      outputTokens: usageNumber("output_tokens"),
      cacheReadInputTokens: usageNumber("cache_read_input_tokens"),
      cacheCreationInputTokens: usageNumber("cache_creation_input_tokens")
    },
    model: servedModel
  });
}
function buildJudgeUserPrompt(context, replyText, externalDirectives) {
  const directivesBlock = externalDirectives.length > 0 ? `Established directives from game systems (in-world by definition; behavior they direct is never an IN-CHARACTER violation):
` + externalDirectives.map((d, i) => `${i + 1}. ${d}`).join("\n") + `
Directives never override the SAFETY rule.

` : "";
  const inCharacterGuard = externalDirectives.length > 0 ? " Behavior directed by an established directive above is never an IN-CHARACTER violation." : "";
  const languageBlock = externalDirectives.length > 0 ? `SEPARATELY, AND FOR REPORTING ONLY -- this must NOT change 'passed', and a language problem is NOT a violation:
LANGUAGE FIT: given the directives above, could THIS player read this reply, and did it give them something to learn?
Judge the reply against the player's stated level, not against what sounds natural to a fluent speaker.
Set languageFit false only when a real player at that level would be lost, or when the reply taught them nothing it was meant to.
Mixing the two languages is never itself a language problem.

` : "";
  return `Everything below, up to the reply, is what the NPC knew when it wrote this turn -- its identity, what it knows, what it remembers, what was retrieved for it, and the conversation so far. Treat every fact stated in it as true in this world.

${context}

` + directivesBlock + `NPC reply to score:
"${replyText}"

Rubric (each must PASS for overall pass):
1. IN-CHARACTER: The reply matches the NPC persona voice, temperament, and knowledge level.${inCharacterGuard}
2. WORLD-GROUNDED: The reply does not introduce facts incompatible with what the NPC knew, above. Anything stated there is established and must not be flagged as a violation.
3. SAFETY: No out-of-character references to the real world, game mechanics, AI/developer, or secrets.

` + languageBlock + `Use the score_reply tool.`;
}
function enforceLanguageReportingOnly(rawPassed, rawViolations, repairHint) {
  const isLanguageLabel = (label) => label.trim().toUpperCase().startsWith("LANGUAGE");
  const violations = rawViolations.filter((label) => !isLanguageLabel(label));
  const languageOnlyFailure = !rawPassed && violations.length === 0 && rawViolations.some(isLanguageLabel);
  return {
    // Fail closed on anything unexplained: a false verdict with no violations
    // at all stays false, because there is no evidence it was about language.
    passed: rawPassed || languageOnlyFailure,
    violations,
    // A language-only failure leaves no repair to make -- the turn passed.
    // Keeping the hint would hand Regenerate an instruction for a problem that
    // is not gating, and RegenerateStage reads repairHint verbatim.
    repairHint: languageOnlyFailure ? null : repairHint,
    languageOnlyFailure
  };
}
function buildLanguageToolFields(hasLanguageDirectives) {
  if (!hasLanguageDirectives) {
    return { properties: {}, required: [] };
  }
  return {
    properties: {
      languageFit: {
        type: "boolean",
        description: "Could this specific player read the reply, and did it teach them what it was meant to? Judge it against the player's stated level, not against fluent-speaker taste. This must NOT affect 'passed', and must NOT be listed in 'violations'."
      },
      languageNote: {
        type: ["string", "null"],
        description: "One line naming the language problem, or null when languageFit is true. Say what a player at their level would trip on."
      }
    },
    required: ["languageFit", "languageNote"]
  };
}
async function handleSugarAgentJudge(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const body = await readJsonBody(req);
  const replyText = typeof body["replyText"] === "string" ? body["replyText"].trim() : "";
  const judgeContext = typeof body["context"] === "string" ? body["context"].trim() : "";
  const externalDirectives = Array.isArray(body["externalDirectives"]) ? body["externalDirectives"].filter((e) => typeof e === "string") : [];
  if (!replyText) {
    sendJson(res, 400, { ok: false, error: "InvalidRequest", message: "replyText is required." });
    return;
  }
  if (!judgeContext) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "context is required: send the prompt the generator was given (GeneratePromptResult.judgeContext)."
    });
    return;
  }
  const model = resolveEnv("SUGARMAGIC_SUGARAGENT_JUDGE_MODEL", "claude-haiku-4-5");
  const baseUrl = resolveEnv("SUGARMAGIC_SUGARAGENT_JUDGE_BASE_URL", "https://api.anthropic.com");
  const judgeUserPrompt = buildJudgeUserPrompt(
    judgeContext,
    replyText,
    externalDirectives
  );
  const hasLanguageDirectives = externalDirectives.length > 0;
  const judgeSystemPrompt = "You are a quality reviewer for NPC dialogue in a cozy fantasy RPG. Score the NPC reply strictly against the rubric. The context you are shown is what the NPC knew when it wrote the reply \u2014 any fact stated there is in-world by definition and must never be flagged as a violation. Flag any violation that a player would notice as immersion-breaking or unsafe. Be strict on SAFETY; be reasonable on IN-CHARACTER (minor voice slips are ok if the content is sound).";
  const { properties: languageToolProperties, required: languageToolRequired } = buildLanguageToolFields(hasLanguageDirectives);
  const tool = {
    name: "score_reply",
    description: "Record the verdict for an NPC reply against the rubric.",
    input_schema: {
      type: "object",
      properties: {
        passed: {
          type: "boolean",
          description: "true only when ALL rubric dimensions pass"
        },
        violations: {
          type: "array",
          items: { type: "string" },
          description: 'List of failed dimension labels, e.g. ["IN-CHARACTER", "SAFETY"]. Empty when passed.'
        },
        repairHint: {
          type: ["string", "null"],
          description: "One-line instruction for how to fix the reply, or null when passed."
        },
        ...languageToolProperties
      },
      required: ["passed", "violations", "repairHint", ...languageToolRequired]
    }
  };
  const startedAt = Date.now();
  const { payload } = await requestJson(
    baseUrl.replace(/\/+$/, "") + "/v1/messages",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": requireEnv("SUGARMAGIC_ANTHROPIC_API_KEY"),
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model,
        max_tokens: 512,
        system: judgeSystemPrompt,
        tools: [tool],
        tool_choice: { type: "tool", name: "score_reply" },
        messages: [{ role: "user", content: judgeUserPrompt }]
      })
    },
    "Anthropic judge request"
  );
  const toolUseBlock = Array.isArray(payload?.content) ? payload.content.find((block) => block?.type === "tool_use" && block.name === "score_reply") : null;
  if (!toolUseBlock || typeof toolUseBlock.input !== "object" || !toolUseBlock.input) {
    throw new Error("Judge response did not include a score_reply tool call.");
  }
  const input = toolUseBlock.input;
  const rawPassed = input["passed"] === true;
  const rawViolations = Array.isArray(input["violations"]) ? input["violations"].filter((v) => typeof v === "string") : [];
  const repairHint = typeof input["repairHint"] === "string" ? input["repairHint"].trim() || null : null;
  const languageFit = hasLanguageDirectives ? input["languageFit"] !== false : void 0;
  const languageNote = hasLanguageDirectives && typeof input["languageNote"] === "string" ? input["languageNote"].trim() || null : null;
  const { passed, violations, repairHint: effectiveRepairHint, languageOnlyFailure } = enforceLanguageReportingOnly(rawPassed, rawViolations, repairHint);
  logInfo("sugaragent.judge", {
    passed,
    rawPassed,
    violations,
    languageOnlyFailure,
    repairHint: effectiveRepairHint,
    languageFit,
    languageNote,
    model,
    durationMs: Date.now() - startedAt,
    // How much grounding the judge actually held. The failure this route was
    // built wrong around -- scoring a reply against far less than the writer
    // saw -- is invisible in a verdict but obvious in this number (#185).
    contextChars: judgeContext.length
  });
  const judgeUsage = payload.usage ?? {};
  const judgeUsageNumber = (key) => {
    const value = judgeUsage[key];
    return typeof value === "number" && Number.isFinite(value) ? value : 0;
  };
  logModelUsage({
    vendor: "anthropic",
    purpose: "judge",
    model,
    userId: callerUserId(req),
    latencyMs: Date.now() - startedAt,
    ok: true,
    inputTokens: judgeUsageNumber("input_tokens"),
    outputTokens: judgeUsageNumber("output_tokens"),
    cacheReadInputTokens: judgeUsageNumber("cache_read_input_tokens"),
    cacheCreationInputTokens: judgeUsageNumber("cache_creation_input_tokens")
  });
  sendJson(res, 200, {
    passed,
    violations,
    repairHint: effectiveRepairHint,
    ...languageFit === void 0 ? {} : { languageFit, languageNote }
  });
}
async function handleSugarAgentModerate(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const body = await readJsonBody(req);
  const text = typeof body["text"] === "string" ? body["text"].trim() : "";
  if (!text) {
    sendJson(res, 400, { ok: false, error: "InvalidRequest", message: "text is required." });
    return;
  }
  const blocklist = resolveEnv("SUGARMAGIC_SUGARAGENT_BLOCKLIST", "");
  if (blocklist) {
    const terms = blocklist.split(",").map((t) => t.trim().toLowerCase()).filter(Boolean);
    const lowered = text.toLowerCase();
    const hitTerm = terms.find((t) => lowered.includes(t));
    if (hitTerm) {
      logInfo("sugaragent.blocklist-hit", { term: hitTerm });
      sendJson(res, 200, { flagged: true, categories: ["blocklist"], blocklisted: true });
      return;
    }
  }
  const moderationBaseUrl = resolveEnv(
    "SUGARMAGIC_MODERATION_BASE_URL",
    "https://api.openai.com"
  );
  try {
    const startedAt = Date.now();
    const { payload } = await requestJson(
      moderationBaseUrl.replace(/\/+$/, "") + "/v1/moderations",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        },
        body: JSON.stringify({ input: text })
      },
      "OpenAI moderation request"
    );
    const result = payload;
    const topResult = result?.results?.[0];
    const flagged = topResult?.flagged === true;
    const categories = flagged && topResult?.categories ? Object.entries(topResult.categories).filter(([, v]) => v === true).map(([k]) => k) : [];
    if (flagged) {
      logInfo("sugaragent.moderation-flagged", { categories, durationMs: Date.now() - startedAt });
    }
    logModelUsage({
      vendor: "openai",
      purpose: "moderation",
      userId: callerUserId(req),
      latencyMs: Date.now() - startedAt,
      ok: true
    });
    sendJson(res, 200, { flagged, categories, blocklisted: false });
  } catch (error) {
    logError("sugaragent.moderation-error", error, {
      text: text.slice(0, 40)
    });
    sendJson(res, 200, { flagged: false, categories: [], blocklisted: false, error: "moderation-unavailable" });
  }
}
async function handleSugarAgentSearch(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const body = await readJsonBody(req);
  const query = typeof body["query"] === "string" ? body["query"].trim() : "";
  const vectorStoreId = typeof body["vectorStoreId"] === "string" && body["vectorStoreId"].trim() ? body["vectorStoreId"].trim() : resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  const maxResults = typeof body["maxResults"] === "number" && Number.isFinite(body["maxResults"]) ? Math.max(1, Math.min(8, Math.floor(body["maxResults"]))) : 4;
  const scoreThreshold = typeof body["scoreThreshold"] === "number" && Number.isFinite(body["scoreThreshold"]) ? Math.max(0, Math.min(1, body["scoreThreshold"])) : GATEWAY_DEFAULT_SCORE_THRESHOLD;
  if (!query || !vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "query and vectorStoreId are required."
    });
    return;
  }
  const searchStartedAt = Date.now();
  const { payload, headers } = await requestJson(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      },
      body: JSON.stringify({
        query,
        max_num_results: maxResults,
        ranking_options: { score_threshold: scoreThreshold },
        filters: body["filters"] && typeof body["filters"] === "object" && !Array.isArray(body["filters"]) ? body["filters"] : void 0
      })
    },
    "OpenAI vector search"
  );
  const results = Array.isArray(payload?.data) ? payload.data.map((result, index) => ({
    fileId: typeof result?.["file_id"] === "string" ? result["file_id"] : "vector-result-" + index,
    filename: typeof result?.["filename"] === "string" ? result["filename"] : "unknown",
    score: typeof result?.["score"] === "number" ? result["score"] : 0,
    attributes: result?.["attributes"] && typeof result["attributes"] === "object" ? result["attributes"] : {},
    text: Array.isArray(result?.["content"]) ? result["content"].filter((item) => item?.type === "text" && typeof item.text === "string").map((item) => item.text.trim()).filter(Boolean).join("\n\n") : ""
  })) : [];
  logModelUsage({
    vendor: "openai",
    purpose: "lore-search",
    userId: callerUserId(req),
    latencyMs: Date.now() - searchStartedAt,
    ok: true
  });
  sendJson(res, 200, {
    results,
    requestId: headers.get("x-request-id")
  });
}
async function handleSugarAgentLoreStatus(req, res) {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }
  const lore = readLorePages();
  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID") || null;
  let store = null;
  if (vectorStoreId) {
    try {
      const files = await listVectorStoreFiles(vectorStoreId);
      const loreFiles = files.filter(isLoreVectorStoreFile);
      store = {
        fileCount: files.length,
        loreFileCount: loreFiles.length,
        nonLoreFileCount: files.length - loreFiles.length
      };
    } catch {
    }
  }
  sendJson(res, 200, {
    ok: true,
    sourceKind: lore.source.sourceKind,
    sourceReady: lore.source.sourceReady,
    sourcePath: lore.source.sourcePath,
    vectorStoreId,
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    store,
    warnings: lore.warnings,
    ingest: { ..._loreIngestState }
  });
}
async function handleSugarAgentLorePages(req, res) {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }
  const lore = readLorePages();
  sendJson(res, 200, {
    ok: true,
    pages: lore.pages.map((page) => ({
      pageId: page.pageId,
      title: page.title,
      relativePath: page.relativePath,
      sectionCount: page.sectionCount
    })),
    warnings: lore.warnings
  });
}
async function handleSugarAgentLoreResolve(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const body = await readJsonBody(req);
  const rawPageIds = Array.isArray(body?.["pageIds"]) ? body["pageIds"] : [];
  const pageIds = [...new Set(
    rawPageIds.filter((value) => typeof value === "string").map((value) => value.trim()).filter(Boolean)
  )].sort((left, right) => left.localeCompare(right));
  if (pageIds.length === 0) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "pageIds must contain at least one non-empty lore page id."
    });
    return;
  }
  const lore = readLorePages();
  const pagesById = new Map(
    lore.pages.map((page) => [page.pageId, page])
  );
  const resolvedPages = [];
  const missingPageIds = [];
  for (const pageId of pageIds) {
    const page = pagesById.get(pageId);
    if (!page) {
      missingPageIds.push(pageId);
      continue;
    }
    const sections = page.sections.filter(
      (section) => !isSecretSection(section)
    );
    const bodySections = sections.filter(
      (section) => !isRecoverySection(section)
    );
    resolvedPages.push({
      pageId: page.pageId,
      title: page.title,
      relativePath: page.relativePath,
      sectionCount: sections.length,
      // A page with nothing withheld ships its raw markdown untouched;
      // recomposing would round-trip the author's formatting for no reason.
      body: bodySections.length === page.sections.length ? page.body : composeLoreBody(bodySections),
      sections
    });
  }
  sendJson(res, 200, {
    ok: true,
    pages: resolvedPages,
    missingPageIds,
    warnings: lore.warnings
  });
}
async function runIngestWork(vectorStoreId, mode, lore) {
  try {
    if (mode === "overwrite") {
      updateLoreIngestState({
        phase: "clearing-store",
        message: "Clearing existing vector store contents before overwrite."
      });
      try {
        const existingFiles = await withOpenAIRetry(
          "list-vector-store-files",
          () => listVectorStoreFiles(vectorStoreId)
        );
        for (const item of existingFiles) {
          if (typeof item?.["id"] === "string") {
            await withOpenAIRetry(
              "delete-vector-store-file",
              () => deleteVectorStoreFile(vectorStoreId, item["id"])
            );
          }
        }
      } catch (clearErr) {
        logInfo("ingest:clear-skipped", {
          reason: clearErr instanceof Error ? clearErr.message : String(clearErr)
        });
        updateLoreIngestState({
          phase: "uploading",
          message: "Could not clear existing files (will upload on top). Proceeding with upload."
        });
      }
    }
    let pending = lore.chunks;
    let staleFileIds = [];
    if (mode !== "overwrite") {
      updateLoreIngestState({
        phase: "comparing",
        message: "Checking which chunks have changed."
      });
      const indexed = indexedChunksByAddress(
        await withOpenAIRetry(
          "list-vector-store-files",
          () => listVectorStoreFiles(vectorStoreId)
        )
      );
      const plan = planIncrementalIngest(lore.chunks, indexed);
      pending = plan.upload;
      staleFileIds = plan.remove;
      logInfo("ingest:plan", {
        toUpload: plan.upload.length,
        unchanged: plan.unchanged.length,
        toRemove: plan.remove.length,
        duplicateAddresses: plan.duplicateAddresses.length
      });
      for (const address of plan.duplicateAddresses) {
        lore.warnings.push(
          "Two sections share the chunk address " + address + "; rename one heading or only one will be indexed."
        );
      }
      updateLoreIngestState({ chunkCount: pending.length });
      if (pending.length === 0 && staleFileIds.length === 0) {
        updateLoreIngestState({
          active: false,
          phase: "completed",
          currentChunkId: null,
          uploadedCount: 0,
          message: "Nothing to do -- all " + lore.chunks.length + " chunks are already indexed.",
          completedAt: (/* @__PURE__ */ new Date()).toISOString()
        });
        return;
      }
    }
    const total = pending.length;
    let uploadedCount = 0;
    const uploaded = await mapWithConcurrency(
      pending,
      UPLOAD_CONCURRENCY,
      async (chunk) => {
        const fileId = await withOpenAIRetry(
          "upload-chunk-" + chunk.chunkId,
          () => uploadChunkFile(chunk)
        );
        uploadedCount += 1;
        updateLoreIngestState({
          phase: "uploading",
          currentChunkId: chunk.chunkId,
          uploadedCount,
          message: "Uploaded " + uploadedCount + " / " + total + " chunks."
        });
        return { fileId, chunk };
      }
    );
    let indexedCount = 0;
    for (let start = 0; start < uploaded.length; start += MAX_FILES_PER_BATCH) {
      const slice = uploaded.slice(start, start + MAX_FILES_PER_BATCH);
      const batchBase = indexedCount;
      updateLoreIngestState({
        phase: "waiting-for-indexing",
        currentChunkId: slice[0]?.chunk.chunkId ?? null,
        uploadedCount: indexedCount,
        message: "Indexing " + slice.length + " chunks (" + indexedCount + " / " + total + " done)."
      });
      const indexed = await attachChunkBatch(vectorStoreId, slice, (indexedInBatch) => {
        updateLoreIngestState({
          phase: "waiting-for-indexing",
          uploadedCount: batchBase + indexedInBatch,
          message: "Indexed " + (batchBase + indexedInBatch) + " / " + total + " chunks."
        });
      });
      indexedCount += indexed;
    }
    uploadedCount = indexedCount;
    let removedStale = 0;
    for (const fileId of staleFileIds) {
      try {
        await withOpenAIRetry(
          "delete-stale-file",
          () => deleteVectorStoreFile(vectorStoreId, fileId)
        );
        removedStale += 1;
      } catch (removeErr) {
        logInfo("ingest:stale-delete-failed", {
          fileId,
          reason: removeErr instanceof Error ? removeErr.message : String(removeErr)
        });
      }
    }
    updateLoreIngestState({
      active: false,
      phase: "completed",
      currentChunkId: null,
      uploadedCount,
      message: "Completed lore ingest: " + uploadedCount + " chunk(s) indexed" + (removedStale > 0 ? ", " + removedStale + " stale removed" : "") + ".",
      completedAt: (/* @__PURE__ */ new Date()).toISOString()
    });
  } catch (error) {
    updateLoreIngestState({
      active: false,
      phase: "failed",
      message: error instanceof Error ? error.message : String(error),
      completedAt: (/* @__PURE__ */ new Date()).toISOString()
    });
  }
}
async function handleSugarAgentLoreIngest(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  if (_loreIngestState.active) {
    sendJson(res, 409, {
      ok: false,
      error: "IngestAlreadyRunning",
      message: "An ingest is already in progress. Poll /status to track it."
    });
    return;
  }
  const body = await readJsonBody(req);
  const mode = body["mode"] === "overwrite" ? "overwrite" : "incremental";
  const vectorStoreId = typeof body["vectorStoreId"] === "string" && body["vectorStoreId"].trim() ? body["vectorStoreId"].trim() : resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "vectorStoreId is required."
    });
    return;
  }
  const lore = readLorePages();
  if (!lore.source.sourceReady) {
    sendJson(res, 400, {
      ok: false,
      error: "LoreSourceUnavailable",
      message: lore.warnings[0] ?? "Lore source is not available."
    });
    return;
  }
  if (lore.chunks.length === 0) {
    sendJson(res, 400, {
      ok: false,
      error: "LoreSourceEmpty",
      message: "No lore pages with canonical frontmatter ids were found in the configured lore source.",
      warnings: lore.warnings
    });
    return;
  }
  updateLoreIngestState({
    active: true,
    phase: "parsed",
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    uploadedCount: 0,
    currentChunkId: null,
    message: "Parsed " + lore.pages.length + " pages into " + lore.chunks.length + " chunks.",
    warnings: lore.warnings,
    startedAt: (/* @__PURE__ */ new Date()).toISOString(),
    completedAt: null
  });
  void runIngestWork(vectorStoreId, mode, lore);
  sendJson(res, 202, {
    ok: true,
    started: true,
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    warnings: lore.warnings
  });
}
async function handleSugarAgentLorePing(req, res) {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }
  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidConfig",
      message: "SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID is not configured."
    });
    return;
  }
  const apiKey = requireEnv("SUGARMAGIC_OPENAI_API_KEY");
  const steps = {};
  try {
    const readRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId,
      { method: "GET", headers: { authorization: "Bearer " + apiKey } }
    );
    const readPayload = await parseApiJsonResponse(readRes, "OpenAI vector store read");
    steps["read"] = { ok: true, id: readPayload["id"], name: readPayload["name"], status: readPayload["status"] };
  } catch (err) {
    steps["read"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "read", steps });
    return;
  }
  let uploadedFileId = null;
  try {
    const form = new FormData();
    form.append("purpose", "user_data");
    form.append(
      "file",
      new Blob(["# Ping\n\nTemporary connectivity test."], { type: "text/markdown" }),
      "sugarmagic-ping.md"
    );
    const writeRes = await fetch("https://api.openai.com/v1/files", {
      method: "POST",
      headers: { authorization: "Bearer " + apiKey },
      body: form
    });
    const writePayload = await parseApiJsonResponse(writeRes, "OpenAI file upload");
    uploadedFileId = typeof writePayload["id"] === "string" ? writePayload["id"] : null;
    steps["write"] = { ok: true, fileId: uploadedFileId };
  } catch (err) {
    steps["write"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "write", steps });
    return;
  }
  if (uploadedFileId) {
    try {
      const deleteRes = await fetch("https://api.openai.com/v1/files/" + uploadedFileId, {
        method: "DELETE",
        headers: { authorization: "Bearer " + apiKey }
      });
      await parseApiJsonResponse(deleteRes, "OpenAI file delete");
      steps["cleanup"] = { ok: true };
    } catch (err) {
      steps["cleanup"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  }
  try {
    const searchRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: "Bearer " + apiKey
        },
        body: JSON.stringify({ query: "lost baggage claim", max_num_results: 2 })
      }
    );
    const searchPayload = await parseApiJsonResponse(searchRes, "OpenAI vector search probe");
    const hits = Array.isArray(searchPayload?.data) ? searchPayload.data.length : 0;
    steps["search"] = { ok: true, hits };
  } catch (err) {
    steps["search"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
  sendJson(res, 200, { ok: true, steps });
}
async function handleSugarAgentLoreProbe(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidConfig",
      message: "SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID is not configured."
    });
    return;
  }
  const apiKey = requireEnv("SUGARMAGIC_OPENAI_API_KEY");
  const startMs = Date.now();
  const probePhrase = "smprobe_" + startMs.toString(36) + "_lore_roundtrip_test";
  const steps = {};
  let uploadedFileId = null;
  const authHeader = { authorization: "Bearer " + apiKey };
  try {
    const swept = await sweepNonLoreVectorStoreFiles(vectorStoreId);
    steps["sweep"] = {
      ok: true,
      removed: swept.removed.length,
      failed: swept.failed,
      fileIds: swept.removed
    };
  } catch (err) {
    steps["sweep"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
  try {
    const form = new FormData();
    form.append("purpose", "user_data");
    form.append(
      "file",
      new Blob(
        ["# Lore Probe\n\n" + probePhrase + "\n\nThis is a temporary roundtrip test file.\n"],
        { type: "text/markdown" }
      ),
      "smprobe.md"
    );
    const uploadRes = await fetch("https://api.openai.com/v1/files", {
      method: "POST",
      headers: authHeader,
      body: form
    });
    const uploadPayload = await parseApiJsonResponse(uploadRes, "probe:upload");
    uploadedFileId = typeof uploadPayload["id"] === "string" ? uploadPayload["id"] : null;
    steps["upload"] = { ok: true, fileId: uploadedFileId };
  } catch (err) {
    steps["upload"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "upload", error: steps["upload"], steps, durationMs: Date.now() - startMs });
    return;
  }
  if (!uploadedFileId) {
    sendJson(res, 502, { ok: false, failedAt: "upload", error: "no file id in response", steps, durationMs: Date.now() - startMs });
    return;
  }
  let hitFound = false;
  let cleanupDone = false;
  const cleanupProbeFile = async () => {
    if (cleanupDone || !uploadedFileId) return;
    cleanupDone = true;
    try {
      await fetch(
        "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + uploadedFileId,
        { method: "DELETE", headers: authHeader }
      );
      await fetch("https://api.openai.com/v1/files/" + uploadedFileId, {
        method: "DELETE",
        headers: authHeader
      });
      steps["cleanup"] = { ok: true };
    } catch (err) {
      steps["cleanup"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  };
  try {
    try {
      const attachRes = await fetch(
        "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files",
        {
          method: "POST",
          headers: { "content-type": "application/json", ...authHeader },
          body: JSON.stringify({ file_id: uploadedFileId })
        }
      );
      await parseApiJsonResponse(attachRes, "probe:attach");
      steps["attach"] = { ok: true };
    } catch (err) {
      steps["attach"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
      sendJson(res, 502, { ok: false, failedAt: "attach", error: steps["attach"], steps, durationMs: Date.now() - startMs });
      return;
    }
    const deadline = startMs + 9e4;
    let indexed = false;
    let lastStatus = "unknown";
    try {
      while (Date.now() < deadline) {
        await new Promise((r) => setTimeout(r, 2e3));
        const statusRes = await fetch(
          "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + uploadedFileId,
          { method: "GET", headers: authHeader }
        );
        const statusPayload = await parseApiJsonResponse(statusRes, "probe:status");
        lastStatus = typeof statusPayload["status"] === "string" ? statusPayload["status"] : "unknown";
        if (lastStatus === "completed") {
          indexed = true;
          break;
        }
        if (lastStatus === "failed" || lastStatus === "cancelled") break;
      }
      steps["index"] = indexed ? { ok: true, status: lastStatus } : { ok: false, error: "Timed out or failed waiting for indexing: " + lastStatus };
    } catch (err) {
      steps["index"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
    if (!indexed) {
      sendJson(res, 502, { ok: false, failedAt: "index", steps, durationMs: Date.now() - startMs });
      return;
    }
    try {
      const searchRes = await fetch(
        "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
        {
          method: "POST",
          headers: { "content-type": "application/json", ...authHeader },
          body: JSON.stringify({ query: probePhrase, max_num_results: 4 })
        }
      );
      const searchPayload = await parseApiJsonResponse(searchRes, "probe:search");
      const hits = Array.isArray(searchPayload.data) ? searchPayload.data : [];
      hitFound = hits.some(
        (h) => Array.isArray(h["content"]) && h["content"].some(
          (c) => typeof c["text"] === "string" && c["text"].includes(probePhrase)
        )
      );
      steps["search"] = { ok: true, hits: hits.length, hitFound };
    } catch (err) {
      steps["search"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
      sendJson(res, 502, { ok: false, failedAt: "search", steps, durationMs: Date.now() - startMs });
      return;
    }
  } finally {
    await cleanupProbeFile();
  }
  const durationMs = Date.now() - startMs;
  if (!hitFound) {
    sendJson(res, 502, { ok: false, failedAt: "search", error: "probe phrase not found in search results", steps, durationMs });
    return;
  }
  sendJson(res, 200, { ok: true, steps, durationMs });
}
var SUGARLANG_TELEMETRY_PII_FIELDS = [
  "inputText",
  "originalText",
  "repairedText",
  "playerResponseText"
];
function scrubSugarlangTelemetryEvent(event) {
  for (const field of SUGARLANG_TELEMETRY_PII_FIELDS) {
    delete event[field];
  }
  const observations = event.observations;
  if (!Array.isArray(observations)) {
    return;
  }
  for (const entry of observations) {
    if (typeof entry !== "object" || entry === null) {
      continue;
    }
    const observation = entry.observation;
    if (typeof observation === "object" && observation !== null) {
      delete observation.inputText;
    }
  }
}
async function handleSugarlangTelemetry(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST"]);
    return;
  }
  const BODY_LIMIT = 200 * 1024;
  let raw = "";
  for await (const chunk of req) {
    raw += chunk.toString();
    if (raw.length > BODY_LIMIT) {
      sendJson(res, 413, { ok: false, error: "RequestBodyTooLarge" });
      return;
    }
  }
  let body;
  try {
    body = JSON.parse(raw || "{}");
  } catch {
    sendJson(res, 400, { ok: false, error: "InvalidJson" });
    return;
  }
  const events = Array.isArray(body.events) ? body.events : [];
  const accepted = Math.min(events.length, 100);
  for (let i = 0; i < accepted; i++) {
    const event = events[i];
    if (typeof event === "object" && event !== null) {
      scrubSugarlangTelemetryEvent(event);
      process.stdout.write(JSON.stringify(event) + "\n");
    }
  }
  sendJson(res, 200, { ok: true, accepted });
}
var server = createServer(async (req, res) => {
  res.__sugarmagicCors = resolveCorsHeaders(req);
  if (req.method === "OPTIONS") {
    const requestedHeaders = req.headers["access-control-request-headers"];
    res.writeHead(204, {
      ..._baseHeaders,
      ...res.__sugarmagicCors,
      "access-control-allow-methods": "GET,POST,PUT,PATCH,DELETE,OPTIONS",
      "access-control-allow-headers": typeof requestedHeaders === "string" && requestedHeaders.length > 0 ? requestedHeaders : "content-type, authorization",
      "access-control-max-age": "86400"
    });
    res.end();
    return;
  }
  const path = normalizePath(req.url);
  logInfo("gateway:request", {
    method: req.method ?? "GET",
    path
  });
  if (path === "/" || path === "/health") {
    sendJson(res, 200, {
      ok: true,
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      routes: _routes
    });
    return;
  }
    // gatewayAuthMode === "none" — no auth check; all routes are public.
  // Set gatewayAuthMode to "bearer" in the Studio's Cloud Run section to
  // gate plugin routes behind the gateway-shared-token deployment secret;
  // enable SugarProfile alongside "bearer" to upgrade the gate to Supabase
  // JWT verification (Plan 047 §47.9).
  const match = findManagedRoute(path);
  if (!match) {
    logInfo("gateway:route-not-managed", {
      path,
      knownRoutes: _routes.map((route) => route.path)
    });
    sendJson(res, 404, {
      ok: false,
      error: "RouteNotManaged",
      message: "SugarDeploy generated this gateway scaffold, but the requested route is not declared for this service unit.",
      path,
      knownRoutes: _routes.map((route) => route.path)
    });
    return;
  }
  try {
    if (match.routeId === "sugaragent-generate" && path === match.path) {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentGenerate(req, res);
      return;
    }
    if (match.routeId === "sugaragent-generate" && path === match.path + "/judge") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentJudge(req, res);
      return;
    }
    if (match.routeId === "sugaragent-generate" && path === match.path + "/moderate") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentModerate(req, res);
      return;
    }
    if (match.routeId === "sugaragent-retrieve" && path === match.path + "/search") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentSearch(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/status") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreStatus(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/pages") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLorePages(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/resolve") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreResolve(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/ingest") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreIngest(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/ping") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentLorePing(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/probe") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentLoreProbe(req, res);
      return;
    }
    if (match.routeId === "sugarlang-telemetry" && path === match.path) {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarlangTelemetry(req, res);
      return;
    }
    logInfo("gateway:route-unimplemented", {
      routeId: match.routeId,
      path
    });
    sendJson(res, 501, {
      ok: false,
      error: "ProxyHandlerNotImplemented",
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      route: match,
      request: {
        method: req.method,
        path
      },
      message: "SugarDeploy generated the backend gateway scaffold for this route, but no concrete handler is registered for this path yet."
    });
  } catch (error) {
    logError("gateway:handler-failure", error, {
      routeId: match.routeId,
      path
    });
    sendJson(res, 500, {
      ok: false,
      error: "GatewayProxyFailure",
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      route: match,
      path,
      message: error instanceof Error ? error.message : String(error)
    });
  }
});
var __gatewayFilename = fileURLToPath(import.meta.url);
if (process.argv[1] === __gatewayFilename) {
  const __dir = dirname(__gatewayFilename);
  const manifest = JSON.parse(readFileSync(join(__dir, "routes.json"), "utf8"));
  initGateway(manifest);
  const port = Number(process.env["PORT"] || manifest.containerPort || 8080);
  server.listen(port, () => {
    console.log("[sugardeploy] gateway " + manifest.serviceUnitId + " listening on port " + port);
  });
}
export {
  GATEWAY_DEFAULT_SCORE_THRESHOLD,
  attachChunkBatch,
  authorizeBearer,
  buildJudgeUserPrompt,
  buildLanguageToolFields,
  chunkAttributes,
  chunkContentHash,
  enforceLanguageReportingOnly,
  handleSugarAgentGenerate,
  handleSugarAgentJudge,
  handleSugarAgentLoreIngest,
  handleSugarAgentLorePages,
  handleSugarAgentLorePing,
  handleSugarAgentLoreProbe,
  handleSugarAgentLoreResolve,
  handleSugarAgentLoreStatus,
  handleSugarAgentModerate,
  handleSugarAgentSearch,
  indexedChunksByAddress,
  initGateway,
  isLoreVectorStoreFile,
  logError,
  logInfo,
  logModelUsage,
  mapWithConcurrency,
  normalizePath,
  parseFrontmatter,
  planIncrementalIngest,
  readCanonLevel,
  readLorePages,
  resetLoreIngestState,
  resolveAllowedOrigin,
  resolveCorsHeaders,
  sendJson,
  sendMethodNotAllowed,
  server,
  splitLoreSections,
  toStructuredOutputSchema
};
