// GENERATED BY SUGARMAGIC - DO NOT EDIT
// src/deployment/gateway/supabase-jwt.ts
import {
  createHmac,
  createPublicKey,
  timingSafeEqual,
  verify as cryptoVerify
} from "node:crypto";
function decodeBase64Url(segment) {
  const normalized = segment.replace(/-/g, "+").replace(/_/g, "/");
  const padding = normalized.length % 4 === 0 ? 0 : 4 - normalized.length % 4;
  return Buffer.from(normalized + "=".repeat(padding), "base64");
}
var __jwksCache = {
  url: "",
  expiresAt: 0,
  keys: []
};
var __JWKS_TTL_MS = 10 * 60 * 1e3;
async function __fetchJwks(jwksUrl) {
  const now = Date.now();
  if (__jwksCache.url === jwksUrl && __jwksCache.expiresAt > now) {
    return __jwksCache.keys;
  }
  let response;
  try {
    response = await fetch(jwksUrl);
  } catch (error) {
    console.error("[sugardeploy] supabase-jwt:jwks-fetch-failed " + JSON.stringify({
      jwksUrl,
      error: error instanceof Error ? error.message : String(error)
    }));
    return null;
  }
  if (!response.ok) {
    console.error("[sugardeploy] supabase-jwt:jwks-non-2xx " + JSON.stringify({
      jwksUrl,
      status: response.status
    }));
    return null;
  }
  let body;
  try {
    body = await response.json();
  } catch (error) {
    console.error("[sugardeploy] supabase-jwt:jwks-bad-json " + JSON.stringify({
      jwksUrl,
      error: error instanceof Error ? error.message : String(error)
    }));
    return null;
  }
  const keys = Array.isArray(body && body.keys) ? body.keys : [];
  __jwksCache.url = jwksUrl;
  __jwksCache.expiresAt = now + __JWKS_TTL_MS;
  __jwksCache.keys = keys;
  return keys;
}
function __jwsSigToDer(rawSig) {
  if (rawSig.length !== 64) return null;
  const r = rawSig.subarray(0, 32);
  const s = rawSig.subarray(32);
  function trim(buf) {
    let i = 0;
    while (i < buf.length - 1 && buf[i] === 0) i++;
    let trimmed = buf.subarray(i);
    if (trimmed[0] & 128) {
      trimmed = Buffer.concat([Buffer.from([0]), trimmed]);
    }
    return trimmed;
  }
  const rTrimmed = trim(r);
  const sTrimmed = trim(s);
  const seqBody = Buffer.concat([
    Buffer.from([2, rTrimmed.length]),
    rTrimmed,
    Buffer.from([2, sTrimmed.length]),
    sTrimmed
  ]);
  return Buffer.concat([Buffer.from([48, seqBody.length]), seqBody]);
}
async function verifySupabaseJwt(req) {
  const supabaseUrl = (process.env["SUGARMAGIC_SUGARPROFILE_SUPABASE_URL"] || "").trim();
  if (!supabaseUrl) return null;
  const jwksUrl = supabaseUrl.replace(/\/+$/, "") + "/auth/v1/.well-known/jwks.json";
  const authHeader = req.headers && req.headers["authorization"] || "";
  const prefix = "Bearer ";
  if (typeof authHeader !== "string" || !authHeader.startsWith(prefix)) return null;
  const token = authHeader.slice(prefix.length).trim();
  if (!token) return null;
  const parts = token.split(".");
  if (parts.length !== 3) return null;
  const [headerB64, payloadB64, signatureB64] = parts;
  let jwtHeader;
  try {
    jwtHeader = JSON.parse(decodeBase64Url(headerB64).toString("utf8"));
  } catch {
    return null;
  }
  if (!jwtHeader || typeof jwtHeader !== "object") return null;
  const alg = jwtHeader["alg"];
  const kid = jwtHeader["kid"];
  if (typeof alg !== "string" || typeof kid !== "string" || !kid) return null;
  if (alg !== "ES256" && alg !== "HS256") return null;
  const keys = await __fetchJwks(jwksUrl);
  if (!keys) return null;
  const jwk = keys.find((entry) => entry && entry["kid"] === kid);
  if (!jwk) return null;
  if (jwk["alg"] && jwk["alg"] !== alg) return null;
  let signature;
  try {
    signature = decodeBase64Url(signatureB64);
  } catch {
    return null;
  }
  const signingInput = Buffer.from(headerB64 + "." + payloadB64, "utf8");
  if (alg === "ES256") {
    if (jwk["kty"] !== "EC" || jwk["crv"] !== "P-256") return null;
    let publicKey;
    try {
      publicKey = createPublicKey({ key: jwk, format: "jwk" });
    } catch (error) {
      console.error("[sugardeploy] supabase-jwt:jwk-import-failed " + JSON.stringify({
        kid,
        error: error instanceof Error ? error.message : String(error)
      }));
      return null;
    }
    const derSig = __jwsSigToDer(signature);
    if (!derSig) return null;
    let valid;
    try {
      valid = cryptoVerify("SHA256", signingInput, publicKey, derSig);
    } catch {
      return null;
    }
    if (!valid) return null;
  } else {
    if (jwk["kty"] !== "oct" || typeof jwk["k"] !== "string") return null;
    let secretBytes;
    try {
      secretBytes = decodeBase64Url(jwk["k"]);
    } catch {
      return null;
    }
    const expectedSig = createHmac("sha256", secretBytes).update(signingInput).digest();
    if (expectedSig.length !== signature.length) return null;
    try {
      if (!timingSafeEqual(expectedSig, signature)) return null;
    } catch {
      return null;
    }
  }
  let payload;
  try {
    payload = JSON.parse(decodeBase64Url(payloadB64).toString("utf8"));
  } catch {
    return null;
  }
  if (payload === null || typeof payload !== "object") return null;
  if (payload["aud"] !== "authenticated") return null;
  const nowSeconds = Math.floor(Date.now() / 1e3);
  if (typeof payload["exp"] !== "number" || payload["exp"] <= nowSeconds) return null;
  if (typeof payload["sub"] !== "string" || !payload["sub"]) return null;
  return {
    userId: payload["sub"],
    email: typeof payload["email"] === "string" ? payload["email"] : null
  };
}

// src/deployment/gateway/lore-designation.ts
var PERSONA_CARD_SECTION_SLUGS = ["persona", "voice"];
var SECRETS_SECTION_SLUG = "secrets";
function isPersonaCardSection(section) {
  return PERSONA_CARD_SECTION_SLUGS.includes(section.slug);
}
function isSecretSection(section) {
  return section.slug === SECRETS_SECTION_SLUG;
}
function designateLoreSections(sections) {
  const personaCard = [];
  const coreKnowledge = [];
  const secrets = [];
  for (const section of sections) {
    if (isSecretSection(section)) {
      secrets.push(section);
    } else if (isPersonaCardSection(section)) {
      personaCard.push(section);
    } else {
      coreKnowledge.push(section);
    }
  }
  return { personaCard, coreKnowledge, secrets };
}
function composeLoreBody(sections) {
  return sections.map(
    (section) => (
      // The implicit pre-heading section (slug "overview") had no heading in
      // the source, so re-emit its content only -- don't inject a synthetic
      // "## Overview" the author never wrote.
      section.slug === "overview" ? section.content : `## ${section.heading}

${section.content}`
    )
  ).join("\n\n");
}

// src/deployment/gateway/core.ts
import { createServer } from "node:http";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, extname, join, relative } from "node:path";
import {
  timingSafeEqual as timingSafeEqual2
} from "node:crypto";
var _routes = [];
var _serviceUnitId = "";
var _targetId = "";
var _loreIngestState = {
  active: false,
  phase: "idle",
  pageCount: 0,
  chunkCount: 0,
  uploadedCount: 0,
  currentChunkId: null,
  message: "Idle",
  warnings: [],
  startedAt: null,
  completedAt: null
};
var _allowedOriginPatterns = [];
function initGateway(manifest) {
  _routes = manifest.routes ?? [];
  _serviceUnitId = manifest.serviceUnitId ?? "";
  _targetId = manifest.targetId ?? "";
  _allowedOriginPatterns = (process.env["SUGARMAGIC_GATEWAY_ALLOWED_ORIGINS"] ?? "").split(",").map((entry) => entry.trim()).filter((entry) => entry.length > 0);
}
function resetLoreIngestState() {
  Object.assign(_loreIngestState, {
    active: false,
    phase: "idle",
    pageCount: 0,
    chunkCount: 0,
    uploadedCount: 0,
    currentChunkId: null,
    message: "Idle",
    warnings: [],
    startedAt: null,
    completedAt: null
  });
}
function resolveAllowedOrigin(origin) {
  if (!origin) return null;
  for (const pattern of _allowedOriginPatterns) {
    if (pattern === origin) return origin;
    const wildcardIndex = pattern.indexOf("*");
    if (wildcardIndex >= 0) {
      const prefix = pattern.slice(0, wildcardIndex);
      const suffix = pattern.slice(wildcardIndex + 1);
      if (origin.length >= prefix.length + suffix.length && origin.startsWith(prefix) && origin.endsWith(suffix)) {
        return origin;
      }
    }
  }
  return null;
}
var _baseHeaders = {
  "content-type": "application/json; charset=utf-8"
};
function resolveCorsHeaders(req) {
  const headers = { vary: "origin" };
  const origin = req?.headers?.origin;
  const echoOrigin = resolveAllowedOrigin(origin);
  if (echoOrigin) {
    headers["access-control-allow-origin"] = echoOrigin;
    headers["access-control-allow-credentials"] = "true";
  }
  return headers;
}
function sendJson(res, statusCode, payload) {
  res.writeHead(statusCode, {
    ..._baseHeaders,
    ...res.__sugarmagicCors ?? {}
  });
  res.end(JSON.stringify(payload, null, 2));
}
function logInfo(message, payload) {
  const suffix = payload && typeof payload === "object" ? " " + JSON.stringify(payload) : payload != null ? " " + String(payload) : "";
  console.log("[sugardeploy] " + message + suffix);
}
function logError(message, error, payload) {
  const details = {
    ...payload && typeof payload === "object" ? payload : {},
    error: error instanceof Error ? error.message : String(error)
  };
  console.error("[sugardeploy] " + message + " " + JSON.stringify(details));
}
function updateLoreIngestState(patch) {
  Object.assign(_loreIngestState, patch);
}
function sendMethodNotAllowed(res, allowed) {
  res.writeHead(405, {
    ..._baseHeaders,
    ...res.__sugarmagicCors ?? {},
    allow: allowed.join(", ")
  });
  res.end(
    JSON.stringify(
      {
        ok: false,
        error: "MethodNotAllowed",
        allowed
      },
      null,
      2
    )
  );
}
function normalizePath(url) {
  return (url || "/").split("?")[0] || "/";
}
function authorizeBearer(req) {
  const expected = process.env["SUGARMAGIC_GATEWAY_SHARED_TOKEN"] || "";
  if (!expected) return false;
  const header = req.headers && req.headers["authorization"] || "";
  const prefix = "Bearer ";
  if (typeof header !== "string" || !header.startsWith(prefix)) return false;
  const presented = header.slice(prefix.length).trim();
  if (!presented) return false;
  const expectedBuf = Buffer.from(expected, "utf8");
  const presentedBuf = Buffer.from(presented, "utf8");
  if (expectedBuf.length !== presentedBuf.length) return false;
  try {
    return timingSafeEqual2(expectedBuf, presentedBuf);
  } catch {
    return false;
  }
}
function resolveEnv(name, fallback = "") {
  const value = process.env[name];
  return typeof value === "string" ? value.trim() || fallback : fallback;
}
function requireEnv(name) {
  const value = resolveEnv(name);
  if (!value) {
    throw new Error("Missing required environment variable: " + name);
  }
  return value;
}
async function readJsonBody(req) {
  let requestBody = "";
  for await (const chunk of req) {
    requestBody += chunk.toString();
  }
  if (!requestBody.trim()) {
    return {};
  }
  try {
    return JSON.parse(requestBody);
  } catch {
    throw new Error("Request body must be valid JSON.");
  }
}
async function parseApiJsonResponse(response, label) {
  const raw = await response.text();
  let payload = null;
  if (raw.trim()) {
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }
  }
  if (!response.ok) {
    throw new Error(
      label + " failed with status " + response.status + (raw.trim() ? ": " + raw : "")
    );
  }
  return payload;
}
async function requestJson(url, options, label) {
  logInfo("upstream:request", {
    label,
    url,
    method: options?.method ?? "GET"
  });
  const response = await fetch(url, options);
  const raw = await response.text();
  let payload = null;
  if (raw.trim()) {
    try {
      payload = JSON.parse(raw);
    } catch {
      payload = raw;
    }
  }
  if (!response.ok) {
    logError(label + " failed", new Error("upstream non-2xx"), {
      url,
      status: response.status,
      body: raw
    });
    throw new Error(
      label + " failed with status " + response.status + (typeof payload === "string" ? ": " + payload : payload && typeof payload === "object" && "error" in payload ? ": " + JSON.stringify(payload) : "")
    );
  }
  return {
    payload,
    headers: response.headers
  };
}
function slugify(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "section";
}
function sanitizeFilename(value) {
  return value.replace(/[^a-z0-9._-]+/gi, "-").replace(/-+/g, "-");
}
function parseFrontmatter(raw) {
  if (!raw.startsWith("---\n")) {
    return {
      metadata: {},
      body: raw
    };
  }
  const closingIndex = raw.indexOf("\n---\n", 4);
  if (closingIndex === -1) {
    return {
      metadata: {},
      body: raw
    };
  }
  const frontmatter = raw.slice(4, closingIndex);
  const body = raw.slice(closingIndex + 5);
  const metadata = {};
  for (const line of frontmatter.split("\n")) {
    const separatorIndex = line.indexOf(":");
    if (separatorIndex === -1) continue;
    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    if (!key) continue;
    metadata[key] = value.replace(/^['"]|['"]$/g, "");
  }
  return {
    metadata,
    body
  };
}
function splitLoreSections(markdown) {
  const lines = markdown.split("\n");
  const sections = [];
  let current = {
    heading: "Overview",
    slug: "overview",
    contentLines: []
  };
  for (const line of lines) {
    const headingMatch = /^(#{1,6})\s+(.+)$/.exec(line.trim());
    if (headingMatch) {
      const content = current.contentLines.join("\n").trim();
      if (content) {
        sections.push({
          heading: current.heading,
          slug: current.slug,
          content
        });
      }
      const heading = headingMatch[2].trim();
      current = {
        heading,
        slug: slugify(heading),
        contentLines: []
      };
      continue;
    }
    current.contentLines.push(line);
  }
  const trailingContent = current.contentLines.join("\n").trim();
  if (trailingContent) {
    sections.push({
      heading: current.heading,
      slug: current.slug,
      content: trailingContent
    });
  }
  return sections.length > 0 ? sections : [
    {
      heading: "Overview",
      slug: "overview",
      content: markdown.trim()
    }
  ];
}
function walkMarkdownFiles(rootDir, currentDir = rootDir, files = []) {
  for (const entry of readdirSync(currentDir, { withFileTypes: true })) {
    const absolutePath = join(currentDir, entry.name);
    if (entry.isDirectory()) {
      walkMarkdownFiles(rootDir, absolutePath, files);
      continue;
    }
    const extension = extname(entry.name).toLowerCase();
    if (extension === ".md" || extension === ".markdown") {
      files.push(absolutePath);
    }
  }
  return files;
}
function resolveLoreSource() {
  const sourceKind = resolveEnv("SUGARMAGIC_LORE_SOURCE_KIND", "local");
  const sourcePath = resolveEnv("SUGARMAGIC_LORE_SOURCE_PATH");
  const repositoryUrl = resolveEnv("SUGARMAGIC_LORE_SOURCE_REPOSITORY_URL");
  const repositoryRef = resolveEnv("SUGARMAGIC_LORE_SOURCE_REPOSITORY_REF", "main");
  if (sourceKind === "github") {
    return {
      sourceKind,
      sourcePath: null,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning: "GitHub-backed lore source resolution is planned but not implemented yet. Use a local checked-out lore repo for now."
    };
  }
  if (!sourcePath) {
    return {
      sourceKind: "local",
      sourcePath: null,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning: "SUGARMAGIC_LORE_SOURCE_PATH is not configured in the gateway environment."
    };
  }
  try {
    const stats = statSync(sourcePath);
    if (!stats.isDirectory()) {
      return {
        sourceKind: "local",
        sourcePath,
        repositoryUrl,
        repositoryRef,
        sourceReady: false,
        warning: "Configured lore source path is not a directory: " + sourcePath
      };
    }
  } catch (error) {
    return {
      sourceKind: "local",
      sourcePath,
      repositoryUrl,
      repositoryRef,
      sourceReady: false,
      warning: "Configured lore source path is not readable: " + sourcePath + " (" + (error instanceof Error ? error.message : String(error)) + ")"
    };
  }
  return {
    sourceKind: "local",
    sourcePath,
    repositoryUrl,
    repositoryRef,
    sourceReady: true,
    warning: null
  };
}
function readLorePages() {
  const source = resolveLoreSource();
  if (!source.sourceReady || !source.sourcePath) {
    return {
      source,
      pages: [],
      chunks: [],
      warnings: source.warning ? [source.warning] : []
    };
  }
  const warnings = source.warning ? [source.warning] : [];
  const pages = [];
  const chunks = [];
  const markdownFiles = walkMarkdownFiles(source.sourcePath);
  for (const absolutePath of markdownFiles) {
    const raw = readFileSync(absolutePath, "utf8");
    const { metadata, body } = parseFrontmatter(raw);
    const pageId = typeof metadata["id"] === "string" ? metadata["id"].trim() : "";
    if (!pageId) {
      warnings.push(
        "Skipped lore page without frontmatter id: " + relative(source.sourcePath, absolutePath)
      );
      continue;
    }
    const relativePath = relative(source.sourcePath, absolutePath);
    const title = typeof metadata["title"] === "string" && metadata["title"].trim() || pageId.split(".").at(-1) || pageId;
    const sections = splitLoreSections(body);
    pages.push({
      pageId,
      title,
      relativePath,
      sectionCount: sections.length,
      body,
      sections
    });
    for (const section of sections) {
      if (isSecretSection(section)) continue;
      const chunkId = pageId + "#" + section.slug;
      const embeddingText = [
        "Page ID: " + pageId,
        "Title: " + title,
        "Section: " + section.heading,
        section.content
      ].filter(Boolean).join("\n\n");
      chunks.push({
        pageId,
        chunkId,
        title,
        sectionHeading: section.heading,
        sectionSlug: section.slug,
        relativePath,
        embeddingText
      });
    }
  }
  pages.sort((left, right) => left.pageId.localeCompare(right.pageId));
  chunks.sort((left, right) => left.chunkId.localeCompare(right.chunkId));
  return {
    source,
    pages,
    chunks,
    warnings
  };
}
async function withOpenAIRetry(label, fn, maxAttempts = 3) {
  let lastError;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;
      const isTransient = error instanceof Error && /status (?:429|50[234])/.test(error.message);
      if (!isTransient || attempt === maxAttempts - 1) throw error;
      const delayMs = 1e3 * (attempt + 1);
      logInfo("upstream:retry", { label, attempt: attempt + 1, delayMs });
      await new Promise((r) => setTimeout(r, delayMs));
    }
  }
  throw lastError;
}
async function listVectorStoreFiles(vectorStoreId) {
  const items = [];
  let after = "";
  while (true) {
    const query = after ? "?after=" + encodeURIComponent(after) : "";
    const { payload } = await requestJson(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files" + query,
      {
        method: "GET",
        headers: {
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        }
      },
      "OpenAI vector store file list"
    );
    const batch = Array.isArray(payload?.data) ? payload.data : [];
    items.push(...batch);
    if (!payload?.has_more || batch.length === 0) {
      break;
    }
    after = typeof batch[batch.length - 1]?.["id"] === "string" ? batch[batch.length - 1]["id"] : "";
    if (!after) break;
  }
  return items;
}
async function deleteVectorStoreFile(vectorStoreId, vectorStoreFileId) {
  await requestJson(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + vectorStoreFileId,
    {
      method: "DELETE",
      headers: {
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      }
    },
    "OpenAI vector store file delete"
  );
}
async function uploadChunkToVectorStore(vectorStoreId, chunk, onProgress = null) {
  onProgress?.({
    phase: "uploading",
    currentChunkId: chunk.chunkId,
    message: "Uploading chunk " + chunk.chunkId
  });
  const fileUpload = new FormData();
  fileUpload.append("purpose", "user_data");
  fileUpload.append(
    "file",
    new Blob([chunk.embeddingText], { type: "text/markdown" }),
    sanitizeFilename(chunk.chunkId) + ".md"
  );
  const uploadResponse = await fetch("https://api.openai.com/v1/files", {
    method: "POST",
    headers: {
      authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
    },
    body: fileUpload
  });
  const uploadPayload = await parseApiJsonResponse(
    uploadResponse,
    "OpenAI file upload"
  );
  const attachResponse = await fetch(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      },
      body: JSON.stringify({
        file_id: uploadPayload["id"],
        attributes: {
          page_id: chunk.pageId,
          chunk_id: chunk.chunkId,
          section_slug: chunk.sectionSlug,
          section_heading: chunk.sectionHeading,
          title: chunk.title,
          relative_path: chunk.relativePath
        }
      })
    }
  );
  const vectorStoreFile = await parseApiJsonResponse(
    attachResponse,
    "OpenAI vector store file attach"
  );
  let attempts = 0;
  while (attempts < 30) {
    onProgress?.({
      phase: "waiting-for-indexing",
      currentChunkId: chunk.chunkId,
      message: "Waiting for indexing for " + chunk.chunkId
    });
    const statusResponse = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + vectorStoreFile["id"],
      {
        method: "GET",
        headers: {
          authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
        }
      }
    );
    const statusPayload = await parseApiJsonResponse(
      statusResponse,
      "OpenAI vector store file status"
    );
    if (statusPayload["status"] === "completed") {
      return vectorStoreFile;
    }
    if (statusPayload["status"] === "failed" || statusPayload["status"] === "cancelled") {
      throw new Error(
        "Vector store file processing failed for " + chunk.chunkId + " with status " + statusPayload["status"]
      );
    }
    await new Promise((resolve) => setTimeout(resolve, 1e3));
    attempts += 1;
  }
  throw new Error(
    "Timed out waiting for vector store processing for chunk " + chunk.chunkId
  );
}
function findManagedRoute(path) {
  return _routes.find(
    (route) => path === route.path || path.startsWith(route.path + "/")
  );
}
async function handleSugarAgentGenerate(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const body = await readJsonBody(req);
  const purpose = typeof body["purpose"] === "string" ? body["purpose"].trim() : "";
  const model = typeof body["model"] === "string" && body["model"].trim() ? body["model"].trim() : purpose === "summary" ? resolveEnv("SUGARMAGIC_SUGARAGENT_SUMMARY_MODEL", "claude-haiku-4-5") : resolveEnv("SUGARMAGIC_SUGARAGENT_ANTHROPIC_MODEL", "claude-haiku-4-5");
  logInfo("sugaragent.generate", { purpose: purpose || "dialogue", model });
  const systemPrompt = typeof body["systemPrompt"] === "string" ? body["systemPrompt"].trim() : "";
  const userPrompt = typeof body["userPrompt"] === "string" ? body["userPrompt"].trim() : "";
  const maxTokens = typeof body["maxTokens"] === "number" && Number.isFinite(body["maxTokens"]) ? Math.max(1, Math.floor(body["maxTokens"])) : 300;
  const rawSystemBlocks = Array.isArray(body["systemBlocks"]) ? body["systemBlocks"] : null;
  const systemBlocks = rawSystemBlocks ? rawSystemBlocks.filter(
    (entry) => !!entry && typeof entry === "object" && typeof entry.text === "string" && entry.text.trim().length > 0
  ).map((entry) => ({
    text: entry.text.trim(),
    cache: entry.cache === true
  })) : null;
  const hasSystemBlocks = !!systemBlocks && systemBlocks.length > 0;
  if (!systemPrompt && !hasSystemBlocks || !userPrompt) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "userPrompt and one of systemPrompt or systemBlocks are required."
    });
    return;
  }
  const anthropicSystem = hasSystemBlocks ? systemBlocks.map((block) => ({
    type: "text",
    text: block.text,
    ...block.cache ? { cache_control: { type: "ephemeral" } } : {}
  })) : systemPrompt;
  const { payload, headers } = await requestJson(
    "https://api.anthropic.com/v1/messages",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": requireEnv("SUGARMAGIC_ANTHROPIC_API_KEY"),
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model,
        max_tokens: maxTokens,
        system: anthropicSystem,
        messages: [
          {
            role: "user",
            content: userPrompt
          }
        ]
      })
    },
    "Anthropic request"
  );
  const text = Array.isArray(payload?.content) ? payload.content.filter((block) => block?.type === "text" && typeof block.text === "string").map((block) => block.text.trim()).filter(Boolean).join("\n\n") : "";
  if (!text) {
    throw new Error("Anthropic response did not include text content.");
  }
  const rawUsage = payload.usage ?? {};
  const usageNumber = (key) => {
    const value = rawUsage[key];
    return typeof value === "number" && Number.isFinite(value) ? value : 0;
  };
  const servedModel = typeof payload.model === "string" && payload.model.trim().length > 0 ? payload.model : model;
  sendJson(res, 200, {
    text,
    requestId: headers.get("request-id"),
    usage: {
      inputTokens: usageNumber("input_tokens"),
      outputTokens: usageNumber("output_tokens"),
      cacheReadInputTokens: usageNumber("cache_read_input_tokens"),
      cacheCreationInputTokens: usageNumber("cache_creation_input_tokens")
    },
    model: servedModel
  });
}
async function handleSugarAgentSearch(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const body = await readJsonBody(req);
  const query = typeof body["query"] === "string" ? body["query"].trim() : "";
  const vectorStoreId = typeof body["vectorStoreId"] === "string" && body["vectorStoreId"].trim() ? body["vectorStoreId"].trim() : resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  const maxResults = typeof body["maxResults"] === "number" && Number.isFinite(body["maxResults"]) ? Math.max(1, Math.min(8, Math.floor(body["maxResults"]))) : 4;
  if (!query || !vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "query and vectorStoreId are required."
    });
    return;
  }
  const { payload, headers } = await requestJson(
    "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + requireEnv("SUGARMAGIC_OPENAI_API_KEY")
      },
      body: JSON.stringify({
        query,
        max_num_results: maxResults,
        filters: body["filters"] && typeof body["filters"] === "object" && !Array.isArray(body["filters"]) ? body["filters"] : void 0
      })
    },
    "OpenAI vector search"
  );
  const results = Array.isArray(payload?.data) ? payload.data.map((result, index) => ({
    fileId: typeof result?.["file_id"] === "string" ? result["file_id"] : "vector-result-" + index,
    filename: typeof result?.["filename"] === "string" ? result["filename"] : "unknown",
    score: typeof result?.["score"] === "number" ? result["score"] : 0,
    attributes: result?.["attributes"] && typeof result["attributes"] === "object" ? result["attributes"] : {},
    text: Array.isArray(result?.["content"]) ? result["content"].filter((item) => item?.type === "text" && typeof item.text === "string").map((item) => item.text.trim()).filter(Boolean).join("\n\n") : ""
  })) : [];
  sendJson(res, 200, {
    results,
    requestId: headers.get("x-request-id")
  });
}
async function handleSugarAgentLoreStatus(req, res) {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }
  const lore = readLorePages();
  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID") || null;
  sendJson(res, 200, {
    ok: true,
    sourceKind: lore.source.sourceKind,
    sourceReady: lore.source.sourceReady,
    sourcePath: lore.source.sourcePath,
    vectorStoreId,
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    warnings: lore.warnings,
    ingest: { ..._loreIngestState }
  });
}
async function handleSugarAgentLorePages(req, res) {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }
  const lore = readLorePages();
  sendJson(res, 200, {
    ok: true,
    pages: lore.pages.map((page) => ({
      pageId: page.pageId,
      title: page.title,
      relativePath: page.relativePath,
      sectionCount: page.sectionCount
    })),
    warnings: lore.warnings
  });
}
async function handleSugarAgentLoreResolve(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const body = await readJsonBody(req);
  const rawPageIds = Array.isArray(body?.["pageIds"]) ? body["pageIds"] : [];
  const pageIds = [...new Set(
    rawPageIds.filter((value) => typeof value === "string").map((value) => value.trim()).filter(Boolean)
  )].sort((left, right) => left.localeCompare(right));
  if (pageIds.length === 0) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "pageIds must contain at least one non-empty lore page id."
    });
    return;
  }
  const lore = readLorePages();
  const pagesById = new Map(
    lore.pages.map((page) => [page.pageId, page])
  );
  const resolvedPages = [];
  const missingPageIds = [];
  for (const pageId of pageIds) {
    const page = pagesById.get(pageId);
    if (!page) {
      missingPageIds.push(pageId);
      continue;
    }
    const hasSecret = page.sections.some(isSecretSection);
    if (!hasSecret) {
      resolvedPages.push({
        pageId: page.pageId,
        title: page.title,
        relativePath: page.relativePath,
        sectionCount: page.sectionCount,
        body: page.body,
        sections: page.sections
      });
      continue;
    }
    const visibleSections = page.sections.filter(
      (section) => !isSecretSection(section)
    );
    resolvedPages.push({
      pageId: page.pageId,
      title: page.title,
      relativePath: page.relativePath,
      sectionCount: visibleSections.length,
      body: composeLoreBody(visibleSections),
      sections: visibleSections
    });
  }
  sendJson(res, 200, {
    ok: true,
    pages: resolvedPages,
    missingPageIds,
    warnings: lore.warnings
  });
}
async function runIngestWork(vectorStoreId, mode, lore) {
  try {
    if (mode === "overwrite") {
      updateLoreIngestState({
        phase: "clearing-store",
        message: "Clearing existing vector store contents before overwrite."
      });
      try {
        const existingFiles = await withOpenAIRetry(
          "list-vector-store-files",
          () => listVectorStoreFiles(vectorStoreId)
        );
        for (const item of existingFiles) {
          if (typeof item?.["id"] === "string") {
            await withOpenAIRetry(
              "delete-vector-store-file",
              () => deleteVectorStoreFile(vectorStoreId, item["id"])
            );
          }
        }
      } catch (clearErr) {
        logInfo("ingest:clear-skipped", {
          reason: clearErr instanceof Error ? clearErr.message : String(clearErr)
        });
        updateLoreIngestState({
          phase: "uploading",
          message: "Could not clear existing files (will upload on top). Proceeding with upload."
        });
      }
    }
    let uploadedCount = 0;
    for (const chunk of lore.chunks) {
      await withOpenAIRetry(
        "upload-chunk-" + chunk.chunkId,
        () => uploadChunkToVectorStore(vectorStoreId, chunk, (progress) => {
          updateLoreIngestState({
            phase: progress.phase,
            currentChunkId: progress.currentChunkId ?? null,
            message: progress.message,
            uploadedCount
          });
        })
      );
      uploadedCount += 1;
      updateLoreIngestState({
        phase: "uploading",
        currentChunkId: chunk.chunkId,
        uploadedCount,
        message: "Uploaded " + uploadedCount + " / " + lore.chunks.length + " chunks."
      });
    }
    updateLoreIngestState({
      active: false,
      phase: "completed",
      currentChunkId: null,
      uploadedCount,
      message: "Completed lore ingest.",
      completedAt: (/* @__PURE__ */ new Date()).toISOString()
    });
  } catch (error) {
    updateLoreIngestState({
      active: false,
      phase: "failed",
      message: error instanceof Error ? error.message : String(error),
      completedAt: (/* @__PURE__ */ new Date()).toISOString()
    });
  }
}
async function handleSugarAgentLoreIngest(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  if (_loreIngestState.active) {
    sendJson(res, 409, {
      ok: false,
      error: "IngestAlreadyRunning",
      message: "An ingest is already in progress. Poll /status to track it."
    });
    return;
  }
  const body = await readJsonBody(req);
  const mode = "overwrite";
  const vectorStoreId = typeof body["vectorStoreId"] === "string" && body["vectorStoreId"].trim() ? body["vectorStoreId"].trim() : resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidRequest",
      message: "vectorStoreId is required."
    });
    return;
  }
  const lore = readLorePages();
  if (!lore.source.sourceReady) {
    sendJson(res, 400, {
      ok: false,
      error: "LoreSourceUnavailable",
      message: lore.warnings[0] ?? "Lore source is not available."
    });
    return;
  }
  if (lore.chunks.length === 0) {
    sendJson(res, 400, {
      ok: false,
      error: "LoreSourceEmpty",
      message: "No lore pages with canonical frontmatter ids were found in the configured lore source.",
      warnings: lore.warnings
    });
    return;
  }
  updateLoreIngestState({
    active: true,
    phase: "parsed",
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    uploadedCount: 0,
    currentChunkId: null,
    message: "Parsed " + lore.pages.length + " pages into " + lore.chunks.length + " chunks.",
    warnings: lore.warnings,
    startedAt: (/* @__PURE__ */ new Date()).toISOString(),
    completedAt: null
  });
  void runIngestWork(vectorStoreId, mode, lore);
  sendJson(res, 202, {
    ok: true,
    started: true,
    pageCount: lore.pages.length,
    chunkCount: lore.chunks.length,
    warnings: lore.warnings
  });
}
async function handleSugarAgentLorePing(req, res) {
  if (req.method !== "GET") {
    sendMethodNotAllowed(res, ["GET", "OPTIONS"]);
    return;
  }
  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidConfig",
      message: "SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID is not configured."
    });
    return;
  }
  const apiKey = requireEnv("SUGARMAGIC_OPENAI_API_KEY");
  const steps = {};
  try {
    const readRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId,
      { method: "GET", headers: { authorization: "Bearer " + apiKey } }
    );
    const readPayload = await parseApiJsonResponse(readRes, "OpenAI vector store read");
    steps["read"] = { ok: true, id: readPayload["id"], name: readPayload["name"], status: readPayload["status"] };
  } catch (err) {
    steps["read"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "read", steps });
    return;
  }
  let uploadedFileId = null;
  try {
    const form = new FormData();
    form.append("purpose", "user_data");
    form.append(
      "file",
      new Blob(["# Ping\n\nTemporary connectivity test."], { type: "text/markdown" }),
      "sugarmagic-ping.md"
    );
    const writeRes = await fetch("https://api.openai.com/v1/files", {
      method: "POST",
      headers: { authorization: "Bearer " + apiKey },
      body: form
    });
    const writePayload = await parseApiJsonResponse(writeRes, "OpenAI file upload");
    uploadedFileId = typeof writePayload["id"] === "string" ? writePayload["id"] : null;
    steps["write"] = { ok: true, fileId: uploadedFileId };
  } catch (err) {
    steps["write"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "write", steps });
    return;
  }
  if (uploadedFileId) {
    try {
      const deleteRes = await fetch("https://api.openai.com/v1/files/" + uploadedFileId, {
        method: "DELETE",
        headers: { authorization: "Bearer " + apiKey }
      });
      await parseApiJsonResponse(deleteRes, "OpenAI file delete");
      steps["cleanup"] = { ok: true };
    } catch (err) {
      steps["cleanup"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  }
  try {
    const searchRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: "Bearer " + apiKey
        },
        body: JSON.stringify({ query: "lost baggage claim", max_num_results: 2 })
      }
    );
    const searchPayload = await parseApiJsonResponse(searchRes, "OpenAI vector search probe");
    const hits = Array.isArray(searchPayload?.data) ? searchPayload.data.length : 0;
    steps["search"] = { ok: true, hits };
  } catch (err) {
    steps["search"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
  sendJson(res, 200, { ok: true, steps });
}
async function handleSugarAgentLoreProbe(req, res) {
  if (req.method !== "POST") {
    sendMethodNotAllowed(res, ["POST", "OPTIONS"]);
    return;
  }
  const vectorStoreId = resolveEnv("SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID");
  if (!vectorStoreId) {
    sendJson(res, 400, {
      ok: false,
      error: "InvalidConfig",
      message: "SUGARMAGIC_SUGARAGENT_OPENAI_VECTOR_STORE_ID is not configured."
    });
    return;
  }
  const apiKey = requireEnv("SUGARMAGIC_OPENAI_API_KEY");
  const startMs = Date.now();
  const probePhrase = "smprobe_" + startMs.toString(36) + "_lore_roundtrip_test";
  const steps = {};
  let uploadedFileId = null;
  const authHeader = { authorization: "Bearer " + apiKey };
  try {
    const form = new FormData();
    form.append("purpose", "user_data");
    form.append(
      "file",
      new Blob(
        ["# Lore Probe\n\n" + probePhrase + "\n\nThis is a temporary roundtrip test file.\n"],
        { type: "text/markdown" }
      ),
      "smprobe.md"
    );
    const uploadRes = await fetch("https://api.openai.com/v1/files", {
      method: "POST",
      headers: authHeader,
      body: form
    });
    const uploadPayload = await parseApiJsonResponse(uploadRes, "probe:upload");
    uploadedFileId = typeof uploadPayload["id"] === "string" ? uploadPayload["id"] : null;
    steps["upload"] = { ok: true, fileId: uploadedFileId };
  } catch (err) {
    steps["upload"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "upload", error: steps["upload"], steps, durationMs: Date.now() - startMs });
    return;
  }
  if (!uploadedFileId) {
    sendJson(res, 502, { ok: false, failedAt: "upload", error: "no file id in response", steps, durationMs: Date.now() - startMs });
    return;
  }
  try {
    const attachRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files",
      {
        method: "POST",
        headers: { "content-type": "application/json", ...authHeader },
        body: JSON.stringify({ file_id: uploadedFileId })
      }
    );
    await parseApiJsonResponse(attachRes, "probe:attach");
    steps["attach"] = { ok: true };
  } catch (err) {
    steps["attach"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "attach", error: steps["attach"], steps, durationMs: Date.now() - startMs });
    return;
  }
  const deadline = startMs + 9e4;
  let indexed = false;
  let lastStatus = "unknown";
  try {
    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 2e3));
      const statusRes = await fetch(
        "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + uploadedFileId,
        { method: "GET", headers: authHeader }
      );
      const statusPayload = await parseApiJsonResponse(statusRes, "probe:status");
      lastStatus = typeof statusPayload["status"] === "string" ? statusPayload["status"] : "unknown";
      if (lastStatus === "completed") {
        indexed = true;
        break;
      }
      if (lastStatus === "failed" || lastStatus === "cancelled") break;
    }
    steps["index"] = indexed ? { ok: true, status: lastStatus } : { ok: false, error: "Timed out or failed waiting for indexing: " + lastStatus };
  } catch (err) {
    steps["index"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
  if (!indexed) {
    sendJson(res, 502, { ok: false, failedAt: "index", steps, durationMs: Date.now() - startMs });
    return;
  }
  let hitFound = false;
  try {
    const searchRes = await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/search",
      {
        method: "POST",
        headers: { "content-type": "application/json", ...authHeader },
        body: JSON.stringify({ query: probePhrase, max_num_results: 4 })
      }
    );
    const searchPayload = await parseApiJsonResponse(searchRes, "probe:search");
    const hits = Array.isArray(searchPayload.data) ? searchPayload.data : [];
    hitFound = hits.some(
      (h) => Array.isArray(h["content"]) && h["content"].some(
        (c) => typeof c["text"] === "string" && c["text"].includes(probePhrase)
      )
    );
    steps["search"] = { ok: true, hits: hits.length, hitFound };
  } catch (err) {
    steps["search"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
    sendJson(res, 502, { ok: false, failedAt: "search", steps, durationMs: Date.now() - startMs });
    return;
  }
  try {
    await fetch(
      "https://api.openai.com/v1/vector_stores/" + vectorStoreId + "/files/" + uploadedFileId,
      { method: "DELETE", headers: authHeader }
    );
    await fetch("https://api.openai.com/v1/files/" + uploadedFileId, {
      method: "DELETE",
      headers: authHeader
    });
    steps["cleanup"] = { ok: true };
  } catch (err) {
    steps["cleanup"] = { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
  const durationMs = Date.now() - startMs;
  if (!hitFound) {
    sendJson(res, 502, { ok: false, failedAt: "search", error: "probe phrase not found in search results", steps, durationMs });
    return;
  }
  sendJson(res, 200, { ok: true, steps, durationMs });
}
var server = createServer(async (req, res) => {
  res.__sugarmagicCors = resolveCorsHeaders(req);
  if (req.method === "OPTIONS") {
    const requestedHeaders = req.headers["access-control-request-headers"];
    res.writeHead(204, {
      ..._baseHeaders,
      ...res.__sugarmagicCors,
      "access-control-allow-methods": "GET,POST,PUT,PATCH,DELETE,OPTIONS",
      "access-control-allow-headers": typeof requestedHeaders === "string" && requestedHeaders.length > 0 ? requestedHeaders : "content-type, authorization",
      "access-control-max-age": "86400"
    });
    res.end();
    return;
  }
  const path = normalizePath(req.url);
  logInfo("gateway:request", {
    method: req.method ?? "GET",
    path
  });
  if (path === "/" || path === "/health") {
    sendJson(res, 200, {
      ok: true,
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      routes: _routes
    });
    return;
  }
    // gatewayAuthMode === "none" — no auth check; all routes are public.
  // Set gatewayAuthMode to "bearer" in the Studio's Cloud Run section to
  // gate plugin routes behind the gateway-shared-token deployment secret;
  // enable SugarProfile alongside "bearer" to upgrade the gate to Supabase
  // JWT verification (Plan 047 §47.9).
  const match = findManagedRoute(path);
  if (!match) {
    logInfo("gateway:route-not-managed", {
      path,
      knownRoutes: _routes.map((route) => route.path)
    });
    sendJson(res, 404, {
      ok: false,
      error: "RouteNotManaged",
      message: "SugarDeploy generated this gateway scaffold, but the requested route is not declared for this service unit.",
      path,
      knownRoutes: _routes.map((route) => route.path)
    });
    return;
  }
  try {
    if (match.routeId === "sugaragent-generate" && path === match.path) {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentGenerate(req, res);
      return;
    }
    if (match.routeId === "sugaragent-retrieve" && path === match.path + "/search") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentSearch(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/status") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreStatus(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/pages") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLorePages(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/resolve") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreResolve(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/ingest") {
      logInfo("gateway:dispatch", {
        routeId: match.routeId,
        path
      });
      await handleSugarAgentLoreIngest(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/ping") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentLorePing(req, res);
      return;
    }
    if (match.routeId === "sugaragent-lore" && path === match.path + "/probe") {
      logInfo("gateway:dispatch", { routeId: match.routeId, path });
      await handleSugarAgentLoreProbe(req, res);
      return;
    }
    logInfo("gateway:route-unimplemented", {
      routeId: match.routeId,
      path
    });
    sendJson(res, 501, {
      ok: false,
      error: "ProxyHandlerNotImplemented",
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      route: match,
      request: {
        method: req.method,
        path
      },
      message: "SugarDeploy generated the backend gateway scaffold for this route, but no concrete handler is registered for this path yet."
    });
  } catch (error) {
    logError("gateway:handler-failure", error, {
      routeId: match.routeId,
      path
    });
    sendJson(res, 500, {
      ok: false,
      error: "GatewayProxyFailure",
      target: _targetId,
      serviceUnitId: _serviceUnitId,
      route: match,
      path,
      message: error instanceof Error ? error.message : String(error)
    });
  }
});
var __gatewayFilename = fileURLToPath(import.meta.url);
if (process.argv[1] === __gatewayFilename) {
  const __dir = dirname(__gatewayFilename);
  const manifest = JSON.parse(readFileSync(join(__dir, "routes.json"), "utf8"));
  initGateway(manifest);
  const port = Number(process.env["PORT"] || manifest.containerPort || 8080);
  server.listen(port, () => {
    console.log("[sugardeploy] gateway " + manifest.serviceUnitId + " listening on port " + port);
  });
}
export {
  authorizeBearer,
  handleSugarAgentGenerate,
  handleSugarAgentLoreIngest,
  handleSugarAgentLorePages,
  handleSugarAgentLorePing,
  handleSugarAgentLoreProbe,
  handleSugarAgentLoreResolve,
  handleSugarAgentLoreStatus,
  handleSugarAgentSearch,
  initGateway,
  logError,
  logInfo,
  normalizePath,
  parseFrontmatter,
  readLorePages,
  resetLoreIngestState,
  resolveAllowedOrigin,
  resolveCorsHeaders,
  sendJson,
  sendMethodNotAllowed,
  server,
  splitLoreSections
};
